### ISSUE TITLE
Season Statistic Gone

### ISSUE THREAD

**Issue by xysa12** [IUrreta/DatabaseEditor#103]
I used the editor in the middle of the season (at  Canadian GP). After using the database editor, all statistics are reset such as total point for driver, constructor, DHL Pit stops, and even all information regarding the results on the previous races. Basically, all statistic are reset to zero. 

Any workaround regarding this issue? 

I use the database editor to edit:
-Races for ATA Qualification
-Engine performance stats
-Staff stats, but not driver.

**Comment by IUrreta** [comment]
This happens because of editing the calendae in the middle of the season, which is highly recommended to not do so in the Readme. If you know how to edit the db with DB browser, it *may* be fixable by resetting the race IDs from the calendar to the ones that were before you edited it.

**Comment by xysa12** [comment]
ok then. thanks. I'll try to edit the calendar before the season starts then.
