### ISSUE TITLE
In Stats Technical Chiefs, staff members with contracts for the next season are not being displayed

### ISSUE THREAD

**Issue by specialcx** [IUrreta/DatabaseEditor#105]
Hello, thank you for this fantastic tool.

I noticed that some individuals are not being displayed in the Stats Technical Chiefs, for example, Diana Romand with StaffId=352.

It appears that they are not included in the SQL results being executed by back.py in the fetch_staff() function.

I have a contract with Diana for the upcoming season, and when I checked the Staff_Contracts table with StaffId 352, I found records with ContractType 2 and 3, but there were no records with ContractType 0 or NULL.

Is there something specific I should do to ensure that Diana Romand's information is displayed correctly in the Stats Technical Chiefs, considering the contract details I mentioned?

Thank you for your assistance.

**Comment by IUrreta** [comment]
You're spot on what's the issue. As I have not played the game much I have not had much time to experiment. Qill be fixed (or at least I will try) in the next update :)
