### ISSUE TITLE
Cant Load it

### ISSUE THREAD

**Issue by Drew1011** [IUrreta/DatabaseEditor#106]
It doesnt let me clone it using the git method saying "could not create work tree dir 'DatabaseEditor'"

Pleas Help

**Comment by IUrreta** [comment]
You're cloning it into a folder where you don't bave write permissions. Try to do it elsewhere

**Comment by Drew1011** [comment]
i followed the vid it just tells me "fatal: could not create work tree dir 'DatabaseEditor': No such file or directory"

**Comment by IUrreta** [comment]
Okay, I gave you the reason, If you are not willing to make any tiny effort to look that error up on tve internet or even try to fix it yourself and are just going to keep whining here that it doesn't work then it's not my problem. There are other alternatives to the git installation.

**Comment by Drew1011** [comment]
i tried the zip but it wont start up.
