### ISSUE TITLE
Can't edit staff stats

### ISSUE THREAD

**Issue by Lkeah** [IUrreta/DatabaseEditor#117]
İ can edit driver's stats, but I can not edit staff stats, and reserve driver contract is not editable for me
![Problem](https://github.com/IUrreta/DatabaseEditor/assets/69638906/e747ce34-942f-4b68-9b4d-d56fa2c17720)

**Comment by IUrreta** [comment]
I know, this issue was already noted on reddit and I have already fixed it.  A patch will come out in the coming days with more bug fixes that will fix this

**Comment by IUrreta** [comment]
Although I have had no issues while editing reserve drivers contracts, I only have been able to replicate the staff stats edit bug

**Comment by Lkeah** [comment]
Okay, ty.
