### ISSUE TITLE
Problems with the editor in preview

### ISSUE THREAD

**Issue by Lucas1134F** [IUrreta/DatabaseEditor#122]
I can't make edits to alpha and willians in contracts, the option doesn't appear.
![Captura de tela 2023-10-08 102553](https://github.com/IUrreta/DatabaseEditor/assets/147323670/2ec0f109-34b7-43d4-a5ab-79609bb31831)

**Comment by IUrreta** [comment]
No, you just have your scaling on your screen up to 150% or something like that. In 1080p screens I believe even with 125% you shoukd be able to see all of them. This has been answered a million times in github, reddit, RD and discord. For firther issues please lookf if it has been answered before
