### ISSUE TITLE
I'm frustrated with this

### ISSUE THREAD

**Issue by Pissd67** [IUrreta/DatabaseEditor#123]
I tried over and over and over hours after hours doing this. I followed all of the steps multiple do overs. I keep getting windows cannot find 'py'. I tried many video's and I keep getting the same issue its so annoying.  All I want to is use this for Fm23 and i gotten so tired I just want to use this to play after work and thats not a lot of time pls help

**Comment by IUrreta** [comment]
And then what's the purpose of this post? To just rant and complain that it's not working for you? I'm sorry but I'm not a big company that can make software that will work just plug and play for every person and every system. I like to do this open source and yes it has its downsides. You could have noticed that in the trouleshoot guide, that has been posted a million times here, reddit or racedepartment there's exactly the problem that you're saying you have, offering oyu solutions in there.

**Comment by Pissd67** [comment]
Its kind of a rant but I am slightly confused I've everything followed the guide multiple times. I had someone else help me who did it themselves and its the same issue. I'm not mad at yo its frustration of why this is not working

**Comment by Zottegie** [comment]
Not working for me either... such a same. I spend almost 2 days to restart and uninstall and reinstall and follow guide and youtube and reddit. But nothing works for me. So weird. I downloaded phyton in windows store and still no change. It's says i cant find PY and i don't see my saves even i put them in directory and ofcourse it is an .sav file. Even i can't connect. Such a shame. I bought that game for this, but if it's not working then yea... i need to wait maybe for another update.
