### ISSUE TITLE
"Something went wrong" when loading a save

### ISSUE THREAD

**Issue by Jonoz1** [IUrreta/DatabaseEditor#124]
When launching the app everything looks ok, but as soon as I load a save something goes wrong. Here's what launch.bat logs:
```
Version: 1.6.3
Requirement already satisfied: websockets in c:\python3.12\lib\site-packages (11.0.3)

up to date in 671ms

21 packages are looking for funding
  run `npm fund` for details

> Database Editor F1M23@1.6.3 start
> electron .


connection handler failed
Traceback (most recent call last):
  File "C:\Python3.12\Lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "C:\Python3.12\Lib\site-packages\websockets\legacy\server.py", line 1186, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "D:\Downloads\DatabaseEditor-1.6.3\DatabaseEditor\back\back.py", line 220, in handle_client
    conn.commit()
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'commit'
```

**Comment by IUrreta** [comment]
That error is normal-ish when closing the tool. If you could provide me with your save file maybe I can take a look at what's happening :)

**Comment by kkhyun112** [comment]
[save2.zip](https://github.com/IUrreta/DatabaseEditor/files/12918966/save2.zip)
I am also experiencing the same issue when loading a new save file created after today's patch. 
Sharing my save file just in case as i am not entirely sure whether my issue is same as Jonoz1. 
Thanks a lot for taking a look into this issue! :)

**Comment by IUrreta** [comment]
Seems to be an issue with today's patch. If you load your save in oyur game with today's patch  it makes it incompatible with the tool. I'll try to look for a fix, but ngl it's not looking good

**Comment by Fazio-01** [comment]
El problema parece ser ocasionado por el parche, a mí tampoco me permite cargar partidas.

**Comment by justinjones102** [comment]
this issue is also happening for me too! Unable to use the DB mod

**Comment by IUrreta** [comment]
> [save2.zip](https://github.com/IUrreta/DatabaseEditor/files/12918966/save2.zip) I am also experiencing the same issue when loading a new save file created after today's patch. Sharing my save file just in case as i am not entirely sure whether my issue is same as Jonoz1. Thanks a lot for taking a look into this issue! :)

Did oyu have other mods installed? Seems that that save is broken. It reads Corrupted Data on my game and the editor also doesn't read it

**Comment by kkhyun112** [comment]
> > [save2.zip](https://github.com/IUrreta/DatabaseEditor/files/12918966/save2.zip) I am also experiencing the same issue when loading a new save file created after today's patch. Sharing my save file just in case as i am not entirely sure whether my issue is same as Jonoz1. Thanks a lot for taking a look into this issue! :)
> 
> Did oyu have other mods installed? Seems that that save is broken. It reads Corrupted Data on my game and the editor also doesn't read it

Hello, 
I believe i did not use any other mods when created attached save file but looks like it was the save file with other mods used. After i create a new save file without touching anything, the tool loaded the save without any issue.
Sorry for causing inconvience!

**Comment by Fazio-01** [comment]
He

> > > [save2.zip](https://github.com/IUrreta/DatabaseEditor/files/12918966/save2.zip) También estoy experimentando el mismo problema al cargar un nuevo archivo guardado creado después del parche de hoy. Comparto mi archivo guardado por si acaso, ya que no estoy del todo seguro de si mi problema es el mismo que el de Jonoz1. ¡Muchas gracias por echar un vistazo a este número! :)
> > 
> > 
> > ¿Oyu tenía otras modificaciones instaladas? Parece que ese guardado está roto. Lee datos corruptos en mi juego y el editor tampoco los lee.
> 
> Hola, creo que no utilicé ninguna otra modificación cuando creé el archivo guardado adjunto, pero parece que era el archivo guardado con otras modificaciones utilizadas. Después de crear un nuevo archivo guardado sin tocar nada, la herramienta cargó el archivo guardado sin ningún problema. ¡Perdón por causar molestias!

Me ha pasado lo mismo, he probado con un nuevo guardo y todo ha ido bien, perdona la falsa alarma.

**Comment by kkhyun112** [comment]
Hello @IUrreta ,
I also created a new save file with only setting the game Hard difficulty mode (New feature in the recent patch)
The save file cannot be loaded in the tool. 
It seems like the tool is not compatitable with new features added to the game in the recent patch yet.
The new save file i tried earlier which worked fine was set to Standard difficulty mode. 
Hope this helps!

**Comment by IUrreta** [comment]
I just released an update yesterday that brings compatibility with 1.9 saves
