### ISSUE TITLE
Run.vbs won't open/ nothing happens

### ISSUE THREAD

**Issue by burgieaintfun** [IUrreta/DatabaseEditor#125]
After following the steps to install the database, I tried to open run.vbs (on my computer it is just called run) nothing happens. I have tried to open it with different programs but they all say they cannot find it or they give a 'false' notification. Did I do something wrong isntalling it or is it something with my computer?

**Comment by IUrreta** [comment]
Try to double click on launch.bat (inside the launcher folder), a command prompt should open up and give you more info on what's happening

**Comment by burgieaintfun** [comment]
It says either, npm: command not found, or 'npm' is not recognized as an internal or external command, operable program or batch file.

**Comment by IUrreta** [comment]
Then you did not install nodejs correctly

**Comment by burgieaintfun** [comment]
It works now. Thank you for your help
