### ISSUE TITLE
Cannot edit calendar at the start of the first season

### ISSUE THREAD

**Issue by Jonoz1** [IUrreta/DatabaseEditor#131]
Thanks for the 1.6.5 update by the way.
For me at least there's a new issue. I can't edit the calendar before even advancing time at all. Gives the usual `"There is already a modified calendar or you already did the first race! Try again next season!"`

**Comment by Jonoz1** [comment]
Actually it looks like it does work in-game, but it doesn't show that in the app

**Comment by IUrreta** [comment]
What dows that mean?

> Actually it looks like it does work in-game, but it doesn't show that in the app

And could you send me your save file so I can check?

**Comment by Jonoz1** [comment]
Oh ffs sorry for bothering you it works perfectly fine I was just confused that when you reopen the app or anything that causes the app to reload the save it shows the default calendar behind the "There is already a modified calendar" text as well as after clicking save changes you can't edit the calendar anymore so I thought it bugged out
