### ISSUE TITLE
Editor not opening

### ISSUE THREAD

**Issue by Wonfo** [IUrreta/DatabaseEditor#136]
Strangely enough it opened before I put the save in the folder, once i put my latest save (save19.sav) i relaunched the editor because the save wasnt appearing in the dropdown and now its not opening, i removed the save and its still not opening

**Comment by IUrreta** [comment]
Without more info I can't help you

**Comment by 198187654321** [comment]
salve il file run quando clicco non succede nulla come mai?

**Comment by 198187654321** [comment]
mi viene fuori run senza vps come risolvo?grazie
