### ISSUE TITLE
Could not connect with backend

### ISSUE THREAD

**Issue by xineda** [IUrreta/DatabaseEditor#14]
I've Python 3.11, nodeJS installed. Win11.

I downloaded the release branch, put a save in the same folder and when I execute "run" I get the UI empty with the "Could not connect with backend" message in red.

Any ideas?

**Comment by IUrreta** [comment]
What's happening is there is a module named websockets that does not come with python by default, so before starting up the tool the start.bat script runs pip install websockets (whch basically installs that library). For some reason, your pc is not finding pip as a command. What version of python are you using? I downloaded the last one yesterday on a new pc and It came with pip installed by default

**Comment by xineda** [comment]
Don't worry. I guess the problem comes from being a new Win11 install. I've some experience programming but my main driver is Linux. I'll sort it out.

Thanks!!

**Comment by IUrreta** [comment]
Yeah but it's strange as literally yesterday I downloaded in a Win11 laptop Python and it had pip installed. It's supposed to be installed by default since 3.4. You can try to install pip manually yourself. If you find the solution, please psot it here!

**Comment by Ma1zzz** [comment]
i got the same problem

**Comment by Ma1zzz** [comment]
fixed i just uninstall python and install the newest

**Comment by xineda** [comment]
Fixed. When the .bat calls the backend with "py back.py" it gave me an error. I replaced it for "python back.py" and got fixed!

**Comment by xineda** [comment]
Just make sure you have a working python install. If unsure uninstall and reinstall it.

Thanks Ignacio.

**Comment by SmalIGraydonGuy** [comment]
How do you edit .bat?

**Comment by SmalIGraydonGuy** [comment]
I have the latest version of python and I uninstalled and reinstalled several times. Every time I get the same error.
