### ISSUE TITLE
npm ERR! code 1  How to solve this problem

### ISSUE THREAD

**Issue by 2801466407** [IUrreta/DatabaseEditor#141]
Version: 1.6.5
Requirement already satisfied: websockets in c:\users\xpy\appdata\local\programs\python\python311\lib\site-packages (12.0)
npm ERR! code 1
npm ERR! path C:\Users\XPY\Desktop\xiug\DatabaseEditor-1.6.5\node_modules\electron
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! RequestError: connect ETIMEDOUT 20.205.243.166:443
npm ERR!     at ClientRequest.<anonymous> (C:\Users\XPY\Desktop\xiug\DatabaseEditor-1.6.5\node_modules\got\dist\source\core\index.js:970:111)
npm ERR!     at Object.onceWrapper (node:events:629:26)
npm ERR!     at ClientRequest.emit (node:events:526:35)
npm ERR!     at origin.emit (C:\Users\XPY\Desktop\xiug\DatabaseEditor-1.6.5\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:495:9)
npm ERR!     at TLSSocket.emit (node:events:514:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
How to solve this problem

**Comment by IUrreta** [comment]
I would suggest deleting the node_modules folder and trying to run it again. Something went wrong when installing electron

**Comment by 2801466407** [comment]
Thank you for finally working it out
