### ISSUE TITLE
Cannot Connect To Backend

### ISSUE THREAD

**Issue by JacFos09** [IUrreta/DatabaseEditor#143]
Hey, I have installed the database, but when I boot it up with the save it says "Could not connect to backend". I am running a new Mclaren save on the 1.9 update. I have Python, GIT and NODE all installed in their newest versions. I have looked on the troubleshoot and tried to reinstall Python. It didnt work, so I tried the bat file. It said 'No Websockets'. I reinstalled the pip and it is still not working. It said that if I am still having problems to put it on here. Any help?

**Comment by JacFos09** [comment]
I have updated my pip files, now the Curl command displays "curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate." Is this normal?

**Comment by jantkac** [comment]
Hi, 
Had a similar issue, this resolved it:
https://stackoverflow.com/questions/47665760/no-module-named-websocket
Precisely this command: pip install "websockets==8.1". 
But maybe the top answer would work for you as well.

**Comment by JacFos09** [comment]
now get the error:

**Comment by IUrreta** [comment]
For me, without having more context looks like you might have more than one python version installed, and you have the library called websockets (required byt he tool) installed in your python 3.11 but when the tool tries to run python it does so with another python version, not finding that library. This is only a theory and might be wrong, but in the Path enviormental variable you might have a path to another python version that you might want to delete
