### ISSUE TITLE
Asyncio loop error

### ISSUE THREAD

**Issue by jantkac** [IUrreta/DatabaseEditor#148]
Everytime I try to run the editor, I got an issue 'Could not connect with backend'. I'm using Python 3.12 
When launching via launch.bat, console throws this:

-------------------------------------------------------------------------------------------------------------------------------------------

Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...55049, 0, 0))>) at D:\Program Files\Python\Python312\Lib\asyncio\proactor_events.py:841
handle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...55049, 0, 0))>) at D:\Program Files\Python\Python312\Lib\asyncio\proactor_events.py:841>
Traceback (most recent call last):
  File "D:\Program Files\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Program Files\Python\Python312\Lib\asyncio\proactor_events.py", line 848, in loop
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\(user)\AppData\Roaming\Python\Python312\site-packages\websockets\server.py", line 103, in __init__
    super().__init__(**kwargs)
  File "C:\Users\(user)\AppData\Roaming\Python\Python312\site-packages\websockets\protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
                       ^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

-------------------------------------------------------------------------------------------------------------------------------------------

Apparently loop command was deprecated for this library since Python 3.10 as per this:
https://bugs.python.org/issue46796

Any ideas how to resolve this? My python knowledge is really superficial.
Thanks.

**Comment by IUrreta** [comment]
I have just upgraded from python 3.8 to python 3.12 and have no issues while running the python backend...

**Comment by jantkac** [comment]
Managed to resolve it. 
I needed to remove every **"loop=loop"** argument **for asyncio.Lock()**, **asyncio.sleep()** and **asyncio.wait()** functions in the file **"(your python version)/site-packages/websockets/protocol.py"**
Apparently there is something wrong in websockets library. I assume you can upgrade/downgrade websockets library to whatever version doesn't contain loop=loop arguments in this file. But trying it via pip didn't work so I edited it manually.
