### ISSUE TITLE
Could not connect with backend

### ISSUE THREAD

**Issue by DjHumildeDev** [IUrreta/DatabaseEditor#151]
la version 1.6.5 no  me conecta con el backend, he seguido todas las guias y alguna que otra issue y nada, en otras versiones anteriores si me conectaba con pruebas que he hecho pero claro, esas tienen el problema de version de los archivos de guardado, alguna idea?

**Comment by IUrreta** [comment]
Ejecuta con el launch.bat que esta en la carpeta launcher y a ver que te sale en la consola

**Comment by DjHumildeDev** [comment]
![databaseeditorcapt](https://github.com/IUrreta/DatabaseEditor/assets/115066754/2fa22049-63c1-43f9-92d1-22faffa6696e)

**Comment by IUrreta** [comment]
La versión 1.6.5 no cambia nada a la hora de ejecutar el programa con python, por lo que debe de haber algo mal en tu instaalción. Si ya has probado las soluciones de la troubleshoot guidey nada ha funcionado, prueba a instalarlo python desde la microsoft store, a alguna gente le ha funcionado

**Comment by DjHumildeDev** [comment]
Perfecto, ya me funciona instalando el python desde la store, muchas gracias
