### ISSUE TITLE
No connect whit backend

### ISSUE THREAD

**Issue by NeMeSiSPlus** [IUrreta/DatabaseEditor#173]
So, i tried everething i could but still don't connect and i don't know why, pls somebody can help me? Thanks

**Comment by RaylanGiveNZ** [comment]
I had the same issue, there is a fix in the Troubleshoot section.  
Uninstall and Reinstall Python.  Fixed it immediately. 
https://github.com/IUrreta/DatabaseEditor/wiki/Troubleshoot-guide
