### ISSUE TITLE
Not being able to scroll down

### ISSUE THREAD

**Issue by pingley94** [IUrreta/DatabaseEditor#174]
It's an interesting situation but let me explain. Say I'm trying to edit contracts, But I need to scroll down to edit Alpha Tauri or Williams.
 I can't, There's no scroll bar on the right side of the screen.
 I can scroll down and look at other drivers, Other scroll bars are there.
 The main one doesn't exist for me.
 It's not just on the contract edit screen but I can't scroll down to edit operation facilities when editing teams.
I don't need a hotfix but hopefully in an update there's a more stable scroll bar.
The main scroll bar was there in Editor 16.5, I just haven't seen it since I updated from 16.5->17.5 and now 17.6

**Comment by IUrreta** [comment]
Jesus christ, sorry for sounding rude but this is NOT an interesting one. This has been answered a trillion times I swear. Just lower your scaling on your screen configuration. Please, look if others have had a similar issue to yours before posting it.

**Comment by pingley94** [comment]
Understood. I see how that makes the screen better but it still doesn't solve the issue. My lowest screen resolution I can get is 100% on my laptop and I still can't see Williams. When I said I need the scroll bar I meant it for that reason.
Also if you couldn't tell that I'm very new to Github, Only now have I realized there's a closed section on the issues tab. Apologies

**Comment by pingley94** [comment]
as interesting as that is. I did change the scale but did not realize my resolution was also altered. I couldn't feel more like an idiot. I also apologize since I didn't realize that you could go into the closed section into the tabs. Sorry
