### ISSUE TITLE
Cant Scroll

### ISSUE THREAD

**Issue by badboyz123** [IUrreta/DatabaseEditor#175]
Hi , I am so sory disturb for this little things, but i cant scroll down for save i dont know why, i am already change scale 100-150% still cant, do you have any ideas for fix this? your program is cooll so i want try it. before patch 1.76 i can scroll down but right now cant,
![Screenshot 2023-12-24 095350](https://github.com/IUrreta/DatabaseEditor/assets/154715841/2f5599b4-4774-4838-b50a-468f1ebf333a)

**Comment by IUrreta** [comment]
Which screen resolution do you have?

**Comment by jmyers123** [comment]
same issue.
![image](https://github.com/IUrreta/DatabaseEditor/assets/155597924/a057f2e4-b150-492d-9820-37f494f737bc)
this is what is looks like and I can't scroll. Tried different resolutions and display scaling but nothing worked. 100% scale just made me able to see more but I still cant scroll or interact with anything.

**Comment by IUrreta** [comment]
Yours looks different, seems like something has not installed propperly because the tool is not applying the styles correctly. I would recommend a clean installation

**Comment by badboyz123** [comment]
> Which screen resolution do you have?

1366x728 resolution, can you help me to fix it?
![image](https://github.com/IUrreta/DatabaseEditor/assets/154715841/3c9c8a4d-18ca-4ce2-8041-cd73bdcb4702)

**Comment by BIAUNTER** [comment]
I had the same problem as you, simply the problem is that on my pc I had the scale at 125% by default, to be able to see everything I changed it to 100%. Then, if you want, you can go back to the same old scale

**Comment by Streli0** [comment]
Hi !
I have the same problem but the difference is my screen is on 1366 x 768 and not on 1920 x 1080. I tried on  1280 x 720 (1.5x the resoltuion of 1920 x 1080) and it stills not working. Idk what can I do...
(sry for bad english level, french are not the best ;) 
![image](https://github.com/IUrreta/DatabaseEditor/assets/144206360/4725327c-a4e1-4dbf-8915-fded462a5af8)

**Comment by Bartu15** [comment]
I also have a problem with this, on the screen scale I'm 100% sure anyway. Instead of changing, I don't know... to a different interface, maybe it would fix it
