### ISSUE TITLE
Not being able to see the full menus in Windows 11

### ISSUE THREAD

**Issue by Naumhmz21** [IUrreta/DatabaseEditor#182]
In Windows 11 versions, you cannot scroll down to the menus, meaning that for example when you want to change drivers you cannot see all of them. Well that's how it is but with most of the menus
![imagen_2024-01-25_114441692](https://github.com/IUrreta/DatabaseEditor/assets/157703234/99f2617f-8da0-4106-80d6-53961b933fda)
![Screenshot_1](https://github.com/IUrreta/DatabaseEditor/assets/157703234/8bc32201-0218-412d-8827-a573eed344d1)

**Comment by IUrreta** [comment]
No. Look at the troubleshoot guide. It's something to do with your screen's resolution
