### ISSUE TITLE
IA

### ISSUE THREAD

**Issue by Pzglobo** [IUrreta/DatabaseEditor#185]
Hola, no se si es realmente un problema muy grave o no ya que antes tenia muchos problemas pero los arregle todos menos este, simplemnte es que en el Prediction, cuando selecciono el Year y le doy a un circuito, o le doy a Configure y a un circuito, no me predice nada, solo me sale el error de Something went wrong. Please restart the tool / Hello, I don't know if it is really a very serious problem or not since I had many problems before but I fixed them all except this one, it is simply that in the Prediction, when I select the Year and click on a circuit, or I click on Configure and a circuit, it doesn't predict anything, I only get the error Something went wrong. Please restart the tool

**Comment by bufu2k24** [comment]
Hello, first of all i want you to thank for those great work!

I also get an error when i try the prediction.
In the log there is only this message: EXCEPTION:Can't get attribute '_PredictScorer' on <module 'sklearn.metrics._scorer' from 'C:\\Users\\XXX\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sklearn\\metrics\\_scorer.py'>
