### ISSUE TITLE
Can't see year 2023-2024

### ISSUE THREAD

**Issue by StukaBoy** [IUrreta/DatabaseEditor#189]
I'm currently at year 2031 and now year 2023 and 2024 are not visible anymore. Is this a bug with the app or is it game save limitation ?

![image](https://github.com/IUrreta/DatabaseEditor/assets/92061505/5eb0b2b8-fa86-469a-8bc3-0a71eb9ef9b5)

**Comment by IUrreta** [comment]
Oof, it might be a game limitation thing, if you could send me your save  so I could take a look I could tell you exactly, you're the firts one that has come up with this issue so I have no idea :)

**Comment by StukaBoy** [comment]
Yup here is my save nad i suppose not everybody goes up to year 2031 when playing lol
[save1.zip](https://github.com/IUrreta/DatabaseEditor/files/14474680/save1.zip)

**Comment by IUrreta** [comment]
Yup, deleted from the database, game onlybhas record from 2025, unfortunately

**Comment by IUrreta** [comment]
Do you have by any chance a previous version of that same save file? like in the year 2027 or smth line that

**Comment by StukaBoy** [comment]
No sorry, the only one I've got from this game is from 2023 but I think it's logical that the game delete years from the save to not have big save file
