### ISSUE TITLE
Cant connect with backend

### ISSUE THREAD

**Issue by SteinRRR** [IUrreta/DatabaseEditor#192]
When i boot up the databaseEditor i keep getting the issue "Could not connect with backend" |

**Comment by scafutto20** [comment]
same here, any fix?

**Comment by RaylanGiveNZ** [comment]
I had the same issue, there is a fix in the Troubleshoot section.  
Uninstall and Reinstall Python.  Fixed it immediately. 
https://github.com/IUrreta/DatabaseEditor/wiki/Troubleshoot-guide
