### ISSUE TITLE
Waiting for connection

### ISSUE THREAD

**Issue by boomzdaydevice** [IUrreta/DatabaseEditor#197]
Hi sorry I'm hoping you can help. I've been searching to see if I can find any solutions to this issue but I've not been able to find anyone else having posted about this.

I've followed the installation video step-by-step, but when I run the program, it opens but shows as "Checking for updates... Waiting for Connection" - No matter how long I leave it for it just stays in this state, neither connects nor gives the "can't connect to backend" error others seem to have encountered.

**Comment by tester344535** [comment]
Same error, any news?
