### ISSUE TITLE
Add editing pit crew

### ISSUE THREAD

**Issue by 0filmastero** [IUrreta/DatabaseEditor#207]
It would be nice to be able to change the **pit crews** - pit stop times, fatigue, attributes, idk what else, ((to make them fast like Red Bull or make them slow as Kick/Sauber :D ). So if you find time for that it would be great.
(I know it's not an issue but idk where else it should be)

**Comment by IUrreta** [comment]
Noted ;)

**Comment by senweg888** [comment]
hello
Maybe the f1 manager 2024 database editor already has all this and much more
I think this editor will be a work of art :)

**Comment by IUrreta** [comment]
This will be in the editor on july 23rd :)
