### ISSUE TITLE
Add new tools to Buff/Nerf parts

### ISSUE THREAD

**Issue by senweg888** [IUrreta/DatabaseEditor#210]
Hello, first of all I want to praise you for the excellent work. secondly, I liked making a suggestion for a future addition to the editor. in the buff/nerf part of the aerodynamic parts, they could put it in detail as in the game and not as it is in general. for example. instead of increasing the chassis by 100% in general, only increasing the engine cooling by 100% and leaving the other 2 variants at 0, which was enough to maintain the car's balance in relation to others, because if you increase the chassis a lot, it increases everything and the car looks much better than the others. I think it would be interesting

**Comment by IUrreta** [comment]
Will be in the editor when the new version comes out :)
