### ISSUE TITLE
'run' doesn't do anything

### ISSUE THREAD

**Issue by N3XUS41** [IUrreta/DatabaseEditor#217]
Hi, I followed the instructions on install precisely, including Python PATH etc. I created the folder on desktop and the DatabaseEditor folder appeared successfully. Yet when I click 'run'... simply nothing happens. No error box or anything.

Any suggestions on how to fix this? I've tried reinstalling everything. Thanks

**Comment by Dergonek** [comment]
Hi, try running Launch and then Run again.

**Comment by Javixu04** [comment]
Same here!
