### ISSUE TITLE
Something went wrong. Please restart the tool

### ISSUE THREAD

**Issue by alleass** [IUrreta/DatabaseEditor#222]
Installed NodeJS and python, then I lauched the editor 
Did everything according to Troubleshoot guide but whenever I try to load a savefile the tool gives me this message:

> Something went wrong. Please restart the tool
 
After loading .sav file green dot becomes a red one
Tried to restart it  several times but it's not helping. The error still appears whenever I load the save.

**Comment by IUrreta** [comment]
Can you send me your save so I can tru to reproduce the bug?
