### ISSUE TITLE
Can't make transfers

### ISSUE THREAD

**Issue by deputyskog** [IUrreta/DatabaseEditor#228]
[log.txt](https://github.com/user-attachments/files/16355734/log.txt)

I cannot make driver transfers with the editor, no matter who I pick or what the contract toggle is set to. I've included the log file.

**Comment by IUrreta** [comment]
Can you send me your save file and tell me what transfer were you trying so I can try to reproduce the issue?

**Comment by deputyskog** [comment]
https://drive.google.com/file/d/135MVm_fTyC9S-nLKCDQLs7D2e7QAQjxZ/view?usp=drive_link This should be the link to my save file. I was trying to move Alonso or Vesti to my team, neither of which worked.

**Comment by IUrreta** [comment]
who did you fire from your team previously?
