### ISSUE TITLE
Not able to load F1 Manager 2024 Create a Team file in Database Editor v2.0.3

### ISSUE THREAD

**Issue by yeetr2324** [IUrreta/DatabaseEditor#234]
Hey, absolutely love your work with the database editor for f1 manager 2023. Currently I'm facing a small issue for my f1 manager 2024 custom team file. I updated the database editor to v2.0.3 and ran it. It opened fine and I uploaded the save file. It shows the message save uploaded successfully and then instantly the database disconnects. Any help regarding the issue is appreciated. I'm attaching a screenshot for the same below.

![Screenshot 2024-07-24 184928](https://github.com/user-attachments/assets/62f4d48f-dcf5-4fc1-aaa1-5f576753f970)

**Comment by IUrreta** [comment]
Please submit your save so I can take a look

**Comment by yeetr2324** [comment]
Where should I submit my save?

**Comment by yeetr2324** [comment]
[Save Game.zip](https://github.com/user-attachments/files/16364581/Save.Game.zip)
Here is the save file.
Can you please respond to this message with what I need to do to fix the database editor.
Thank You

**Comment by IUrreta** [comment]
Man for me it's loading normally, can you send me your log.txt? Maybe that can give me a hint at what's happening to you

**Comment by yeetr2324** [comment]
Hey, I just loaded it right now, and it works perfectly fine. I'm attaching the log file just in case you wanna check it out. Also I just had a question that in the editor, for the configuration tab, the logo that we upload, does it show up in the game as well anywhere ? Really appreciate the work you have done on this. 
[log file.zip](https://github.com/user-attachments/files/16367948/log.file.zip)

**Comment by Dylan2003vd** [comment]
Hello, i have a issue following the editor, every time i try to edit something it says: something went wrong restart the tool and try again, is there something wrong in my setup or anything? and is there a way the fix this?
i would like to hear about this, because the editor makes the game so much more fun.
Kind Regard,
Dylan

**Comment by connorgibby** [comment]
I have put my save file "steam_autocloud.vdf" into the file for the database editor and nothing happens
