### ISSUE TITLE
I followed all the steps, and still can't get it to run.

### ISSUE THREAD

**Issue by ufhifjifj** [IUrreta/DatabaseEditor#236]
I have tried multiple times to get it to work, I have deleted and restarted the files a lot of times, and yet every time i press run,
it pops up with a command prompt, which is weird cos I followed the steps and this has never happened for me on previous versions of Database Editor. If I have done something wrong please tell me.
(https://github.com/user-attachments/assets/51236367-d164-46ff-82e3-f730a9b6a72f)

**Comment by ufhifjifj** [comment]
NEVERMIND I DONE IT

**Comment by MrFreezing6** [comment]
Hello, how did you solve this problem, I also have the exact same problem as you
