### ISSUE TITLE
[Manager 24] Saving "Performance" in Custom Teams doesn't work

### ISSUE THREAD

**Issue by jonaaa20** [IUrreta/DatabaseEditor#241]
![electron_rn4ebMgNVh](https://github.com/user-attachments/assets/af13af3e-42fd-4b96-921d-61b8550ea677)

Save attached.

[savegame.zip](https://github.com/user-attachments/files/16364507/savegame.zip)

**Comment by IUrreta** [comment]
Will take a look, thanks

**Comment by jonaaa20** [comment]
Here's the error message in text, if you need as well:

[log_error.txt](https://github.com/user-attachments/files/16367176/log_error.txt)

**Comment by IUrreta** [comment]
Solved, the issue was caused by editing performance the 1st day of the save. The fix will be out tomorrow in a patch :)
