### ISSUE TITLE
Cant hire drivers for teams

### ISSUE THREAD

**Issue by KB0ne7** [IUrreta/DatabaseEditor#247]
Using 2.0.4, firing drivers is fine but hiring/transfering drivers into the now vacant seats causes the tool to disconnect and ask for me to restart. Upon restarting, both the seat that I was trying to put a driver in and the former seat where the driver was transfering from is now vacant.

**Comment by KB0ne7** [comment]
[log.txt](https://github.com/user-attachments/files/16373143/log.txt)
Log attached

**Comment by KB0ne7** [comment]
To add further detail to the above, trying to sack Perez and replace him with Ricciardo while adding Lawson into the VCarb. It will say succesfully fired Perez, successfully hired Ricciardo and then say restart when adding Lawson to VCarb. Upon restarting the too, all 3 drivers will now not be assigned a team while all 3 slots are now vacant.

**Comment by IUrreta** [comment]
Yes I am stupid, uploading fix now lol

**Comment by KB0ne7** [comment]
Out of curiousity, what was the issue? haha :)

**Comment by IUrreta** [comment]
I added some code to remove drivers racing from f2 if you swapped and affiliate with a normal driver and I just wrote the worst code I have ever seen in my entire life

**Comment by KB0ne7** [comment]
No worries! Thanks for your work :)

**Comment by KB0ne7** [comment]
Thought I'd post the log as it still doesn't work with 2.0.5 and keep the issue open for you, I will wait till you release so no rush 👍 
[log.txt](https://github.com/user-attachments/files/16373283/log.txt)

**Comment by IUrreta** [comment]
Should be fixed in 2.0.6. Please confirm when you can :)

**Comment by KB0ne7** [comment]
Reopened the game to test, tool worked fine. Pasted the save file back in to folder and the changes didn't save. Moved save back into DatabaseEditor folder and all the changes were gone minus any attribute changes I did. Only the contracts didn't save even though the tool said successful. Log attached again.
[log.txt](https://github.com/user-attachments/files/16373450/log.txt)

**Comment by IUrreta** [comment]
I'm sorry but if the changes didn't save then mostt likely thing that happened is that you moved the wrong save into the game folder or into another folder. To get this more clear, the notification of changed made succesfully will never appear on screen if the changes have not been saved

**Comment by IUrreta** [comment]
Will look into it, most likely I messed up something again

**Comment by KB0ne7** [comment]
No problem, I won't be able to retest until later this evening now. Again, thank you for your hard work :)
________________________________

**Comment by IUrreta** [comment]
Okay, yep, totally my fault, driver transfers is just a hot mess atm and although I think now everything should work I will refactor that whole thing soon because now it's just hell
