### ISSUE TITLE
Font size is too big

### ISSUE THREAD

**Issue by ivalandros** [IUrreta/DatabaseEditor#25]
Hi I cannot edit alpha tauri or Williams because the size of the letter is too big and there is no a bar to access the teams below, is there a possibility to fix it?

![image](https://github.com/IUrreta/DatabaseEditor/assets/141074913/dab4daf5-f4a4-429d-adfb-265e0037b9a9)

**Comment by IUrreta** [comment]
I'll try to look for a solution for the next update. For now, I think on windows If you go into Settings > Sytem > Screen You should have something like Scale and distribution and it should be on 100%. Try to change it to a smallee value lile 75%. I know it's not ideal but I'll try to fix it.

**Comment by ivalandros** [comment]
Yes I try that but it didnt work

**Comment by ivalandros** [comment]
I would try it thanks
