### ISSUE TITLE
Cost cap not changing

### ISSUE THREAD

**Issue by Luko001** [IUrreta/DatabaseEditor#260]
I have edited other aspects of finances successfully, but the cost cap spent has not changed in game when edited. I have tried advancing and simming races, but the cost cap spent change is only shown in the editor, and not in the game itself.

**Comment by IUrreta** [comment]
When editing the Cost cap spent, changes will not be shown in the main cost cap screen in-game, as there is no way to edit it in that window. When you design or research a new part in-game you should see changes applied in the window that appears to confirm the transaction. At least this was how it worked in 23
