### ISSUE TITLE
Cannot edit calendar in S2

### ISSUE THREAD

**Issue by JacFos09** [IUrreta/DatabaseEditor#263]
Hey! I am loving the editor and have used it during Season 1 of my Create a Team, however once I have switched over to S2 (2025), I am able to edit everything except the Calendar. If I try and delete races, or even switch the order of the races, the Editor disconnects and says I have to restart the tool. Is there anything that can be done, or do I just have to play with the regular calendar?

**Comment by IUrreta** [comment]
Can you send me your save and send me the log file so I can take a look? 😀

**Comment by IUrreta** [comment]
Fixed in the latest version
