### ISSUE TITLE
unable to transfer drivers

### ISSUE THREAD

**Issue by ThePlayer3206** [IUrreta/DatabaseEditor#264]
Hi! While editing my F1 Manager 23 save, every time that i try to sign a driver to any team, I get the "something went wrong" error. I updated everything to a newest version, still doesn't work. Any idea what the issue might be?

**Comment by IUrreta** [comment]
Will look into it. Can you send me your save and log?

**Comment by ThePlayer3206** [comment]
[Save and Log.zip](https://github.com/user-attachments/files/16396426/Save.and.Log.zip)

**Comment by IUrreta** [comment]
Found the issue, will be fixed in the next update, thanks!
