### ISSUE TITLE
alfa romeo and alpha tauri appearing on a F1 Manager 24 save

### ISSUE THREAD

**Issue by HGG10** [IUrreta/DatabaseEditor#273]
i created a new carrer and went to the database to see the update, i charged the save and instead of Stake Kick Sauber and VCARB, Alfa Romeo and Alpha Tauri are appearing. in the game Stake Kick Sauber and VCARB appear as its suposed to do, if the problem is fixed with the time i will notice it.
![Captura de pantalla (289)](https://github.com/user-attachments/assets/618f98b7-e82f-4d8a-8e9d-9b88b36fd3ab)
![Captura de pantalla (290)](https://github.com/user-attachments/assets/52da45e3-3101-4497-a9c4-b5c272886777)
![Captura de pantalla (291)](https://github.com/user-attachments/assets/2ca11697-126c-4fb5-9121-1f575620e81b)
![Captura de pantalla (292)](https://github.com/user-attachments/assets/b296a4e8-a953-4a68-b5ee-181f2429163d)

**Comment by IUrreta** [comment]
What did you select in the custom configuration modal? or have you edited the config file?

**Comment by HGG10** [comment]
i didnt do anything, beacouse i started the career today and i didnt edit the config of the file, but if i open it in a career with a real team (started 5 days ago) appears as Stake Kick Sauber and VCARB as you can see here:
![Captura de pantalla (294)](https://github.com/user-attachments/assets/468b998f-9c20-4632-b306-def4a275132f)
![Captura de pantalla (295)](https://github.com/user-attachments/assets/d0b9f3eb-354d-4f61-97fd-7ce4668de370)
![Captura de pantalla (293)](https://github.com/user-attachments/assets/337f476a-7bca-41a8-af0a-0ef5cdf64cd0)

**Comment by IUrreta** [comment]
en principio aunque sea con un equipo ficticio con que le des a no en el modal en el que te pregunta se deberia de poner bien, si quieres si se te ha crerado un fichero de ocnfiguracion para esa partida en la carpeta configs borralo y vuelve a seleccionar la partida en el editor

**Comment by HGG10** [comment]
vale, ya está solucionado. cuando puse el primer comentario no me había salido el modal, ahora me ha salido y he hecho lo que has dicho. gracias
