### ISSUE TITLE
crash after making a future contract to drivers

### ISSUE THREAD

**Issue by HGG10** [IUrreta/DatabaseEditor#276]
crash after making a future contract to bearman with haas
![Captura de pantalla (296)](https://github.com/user-attachments/assets/ded051b0-601f-4400-aa04-d21ed064d0a0)
![Captura de pantalla (297)](https://github.com/user-attachments/assets/ea7eae36-2dcd-49a3-9260-491a09da928f)

**Comment by IUrreta** [comment]
No pongas issues en español. Pasame el logtxt para ver que pasa porque a mi no me da error

**Comment by HGG10** [comment]
[log.txt](https://github.com/user-attachments/files/16405010/log.txt)

**Comment by IUrreta** [comment]
No need to send the log.txt, when you select the team, you have to click the add future contract and then the contract options will deploy (despues de seleccionar el equipo tienes que darle a "Add future contract")

**Comment by HGG10** [comment]
ok
