### ISSUE TITLE
Struggling to save stats

### ISSUE THREAD

**Issue by aaaollie** [IUrreta/DatabaseEditor#28]
Hi all, just struggling to wrap my head around what's happening at the moment, My save is registered and loads in the Database but whenever I try to save it and reload no stats or overall is changed in F1 Manager 23. I'm guessing I'm missing something I've just not been able to wrap my head around it

**Comment by IUrreta** [comment]
If when you hit Save Changes you see the message confirming that that driver's stats have been changed, either you are not placing your save back in your game folder, or you are selecting the wrong save
