### ISSUE TITLE
Forecast doesn't work

### ISSUE THREAD

**Issue by milanwrld** [IUrreta/DatabaseEditor#281]
When I try to predict even just a race it says something went wrong, please restart the tool.

**Comment by IUrreta** [comment]
What race are you trying to predict? Send me the save

**Comment by milanwrld** [comment]
2026 Bahrain 
https://filebin.net/9yiyg7nujc1jwllt/save1.sav

**Comment by IUrreta** [comment]
might be because there is a place open at williams, but I tried signing one driver and didn't work. Will have to take a deeper look. But also, it is not advised to predict the first race of a season
