### ISSUE TITLE
[BUG] Transferring affiliate to race seat

### ISSUE THREAD

**Issue by KB0ne7** [IUrreta/DatabaseEditor#291]
**Describe the bug**
Tool wants a restart

**To Reproduce**
1. Move affiliate to race seat

**Expected behavior**
Tool breaks

**Save file and log.txt**
[log.txt](https://github.com/user-attachments/files/16422924/log.txt)

**Comment by KB0ne7** [comment]
Managed to force it by sacking the affiliate using the tool and offering contract in game followed by editing the contract

**Comment by IUrreta** [comment]
Will be fixed today in a patch

**Comment by IUrreta** [comment]
There's literally an issue from yesterday reporting this as well, please look at previous issues
