### ISSUE TITLE
Everything downloads properly, but when i try to run ,,run.bat" it shows some codes and quickly closes and nothing happens.[BUG]

### ISSUE THREAD

**Issue by Jindrapesl** [IUrreta/DatabaseEditor#294]
**Describe the bug**
Hello,
I was just wondering if anybody else experienced this problem, that everything downloads properly, but when you try to open it it says some codes, then quickly closes and nothing happens.
Anybody knows what to do?

**Comment by IUrreta** [comment]
What does the console say before closing? most likely an issue with electron downlolad, delete node_modules folder from the Database Editore folder and try to run again

**Comment by Jindrapesl** [comment]
> What does the console say before closing? most likely an issue with electron downlolad, delete node_modules folder from the Database Editore folder and try to run again

So,
I tried to delete the node modules and when I tried to run it again it said ,, Virtual enviroment found, downloading requirments"
And it downloads the node modules again.
Anyways it is something to do with the electron or something cause it says that there has been some problem with the electron.
I really don't know what to do.

**Comment by Jindrapesl** [comment]
And also I cannot find my saves anywhere. Cause when I go inside the folder it looks like this
![Snímek obrazovky 2024-07-30 171508](https://github.com/user-attachments/assets/3f2bbcd4-cdf0-49f0-bcc9-f06072cd023c)

**Comment by IUrreta** [comment]
Are you trying to download from China ir Asia? Electron normally gives issues for downloading it from those places. And for the saves, for the love of god, READ the Set up: https://github.com/IUrreta/DatabaseEditor/wiki/Installation-and-set%E2%80%90up-guide

**Comment by Jindrapesl** [comment]
Sorry for bothering you again but,
it still doesn't start. Btw I'm downloading from Europe.
I'll put here a photo what it says....
![Snímek obrazovky 2024-07-30 174259](https://github.com/user-attachments/assets/7d8d4f1d-3134-4b7e-92b7-e670c8be027c)

**Comment by CyberN70** [comment]
I had the same problem. I tried deleting the 'node_modules' folder and then running the script again. After that You have to wait until everything is installed. Make sure you don't close the window and this should normally resolve the issue.

For your saves, they are **not** in the steam folder, look at the last part of the guide that IUrreta gave you previously.

**Comment by Jindrapesl** [comment]
Yeah,
solved the problem already yesterday.
Thank you for your reply anyways
