### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by tomde29** [IUrreta/DatabaseEditor#299]
Be able to change rules that get changed with votes throughout the game. For example the points system or engine amounts

**Comment by IUrreta** [comment]
Tried this a few years ago and had no luck, so it's not looking good

**Comment by knueven** [comment]
This sort of regulation appears to be in `Regulations_Enum_Changes` in the DB, though it's likely more complex than just editing the value if every team has to be issued the parts before the season starts.

Is a shame, was going to make this feature request myself :)
