### ISSUE TITLE
Audi, Renault and Porsche doesnt work on f1 manager 23

### ISSUE THREAD

**Issue by hoksik** [IUrreta/DatabaseEditor#300]
Like i said in title - after i launch app for the first time i select those 3 teams from customize menu, but after setting up save and launching the game, i see old team alfa romeo, alpine and alpha tauri

**Comment by IUrreta** [comment]
"Custom configuration files only serve to modify the aspect of the Database Editor. They will alow you to change names and colors of teams like Alpha Tauri to their 2024 variations like RB Visa Cashapp (or other names and teams from mods installed)"

Like I said, if you read you'll understand things work. Where do I mention that changing thos wilil affect your game?
