### ISSUE TITLE
BUG in Cost Cap Spent

### ISSUE THREAD

**Issue by francesc2651** [IUrreta/DatabaseEditor#301]
La edición del coste máximo gastado ("Cost cap spent") no funciona (en el apartado "Equipos"). Conforme modificas el número para intentar aumentar o disminuirlo y lo guardas como tal, no funciona. Actualizas la página y hay un sustancial aumento del mismo, sin nada que ver con el que tú has puesto. Tampoco funciona ponerlo en negativo para restarlo.

**Comment by IUrreta** [comment]
Don’t post issues on spanish. It’s being investigated.
