### ISSUE TITLE
How can I use custom configuration [BUG]

### ISSUE THREAD

**Issue by Piecykppp** [IUrreta/DatabaseEditor#302]
![image](https://github.com/user-attachments/assets/e38b8e63-fb99-4a2e-84c6-5f91ec70317e)
click yes and:
![image](https://github.com/user-attachments/assets/3fb3ebdc-8f89-45d9-92a7-4fbecf0ddbbc)
what should I do. where should I add these modifications?
f1 manager 24

**Comment by IUrreta** [comment]
If your save is from F1M24 and not a Creat a Team there is nothing to customize
