### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by VagnerBauru** [IUrreta/DatabaseEditor#313]
* Possibility of changing the titles of the attributes (CORNERING, BRAKING, CONTROL...) as is done in the name.
* Possibility of changing the nationality
* Possibility of editing the performance of each part of the car, for example: POWERTRAINS, CHASSIS, FRONT WING...
* In TEAMS, have a button to make the "facilities" 100%, not just the "up" and "down".
* Possibility of adding your own logo within the game.

**Comment by IUrreta** [comment]
Thank you for the suggestions but only number 4 is possible, maybe nationality as well but idk
