### ISSUE TITLE
Run.vbs file not working

### ISSUE THREAD

**Issue by AlessandroPaoloColombo** [IUrreta/DatabaseEditor#32]
I am having some problems getting the "run.vbs" file to work.
Every time that i open the file with python it just opens and immediately closes/crashes python, the only way to open the database for me is to open the "launch.bat" file however when i try to change something in the database with this method (tried both transfers and stats) the game crashes when i start any quali session (the practice sessions seem to run well however). The crash report is the following: "unhandled exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000028".
Can you tell me what am i doing wrong and how can i get the script to work properly?

**Comment by IUrreta** [comment]
If you do driver transfers while or the day before a race weekend the game might crash. If that's the case, maybe try to do it on any other normal day. If it's not the case, you can send me your save file and log.txt so I can see if there's something up there

**Comment by AlessandroPaoloColombo** [comment]
thank you, now it works.
