### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by loekie2005** [IUrreta/DatabaseEditor#322]
**Could not connect to back end and 21 packages ar elooking for funding RUN npm FUND for details**

**To Reproduce**
1. Go to RUN.bat.'
2. Click on 'RUN.bat
3. Wait for error to pop up and then it wil start but cant connect with backend (I already solved a python eror)

**Expected behavior**
Normaly needs to start 

**Save file and log.txt**
RUN.BAT
![image](https://github.com/user-attachments/assets/c0270198-82a0-4bb3-91ec-09a5532b5b00)

**Additional context**
Doesnt start like this

**Comment by IUrreta** [comment]
https://github.com/IUrreta/DatabaseEditor/wiki/Troubleshoot-guide

**Comment by loekie2005** [comment]
i cant figure out why PIP is not working i reinstalled python for a few times but still cant fix this
