### ISSUE TITLE
App doesnt open when i start RUN

### ISSUE THREAD

**Issue by tomopjemuil** [IUrreta/DatabaseEditor#323]
![image](https://github.com/user-attachments/assets/94cf6c46-8623-4af3-8ea5-84cc081aa10c)

Nothing happends when i open the run file.

**Comment by IUrreta** [comment]
Does the console close after that?

**Comment by tomopjemuil** [comment]
I upgraded the PIP, but still an error.
![image](https://github.com/user-attachments/assets/1a1665a7-d255-4d3a-853e-07c65dee3896)

![image](https://github.com/user-attachments/assets/b9f711f7-fbf6-48a1-9fe4-5aa604d34c52)

**Comment by tomopjemuil** [comment]
> Does the console close after that?

Yep, instantly, had too time the screenshot perfectly

**Comment by IUrreta** [comment]
Delete node_modules folder (inside the Editor folder) and try to run again

**Comment by tomopjemuil** [comment]
Thanks foir the quick response! 
I can't find that 
![image](https://github.com/user-attachments/assets/594df9f2-aeaf-4b02-be0c-da54b20fcb3e)

**Comment by IUrreta** [comment]
Ah okay I see what's happening, you didn't install nodeJS correclty, it's saying npm is not recognized as a command

**Comment by tomopjemuil** [comment]
THanks man! i am so dumb sometimes. Thanks for the help and the program!

**Comment by IUrreta** [comment]
Does it work?

**Comment by tomopjemuil** [comment]
Yep, your program works perfect. I will test it out with the f1 mngr 2024 game on monday. I don’t have time to game now. Again thanks for the help man!

**Comment by SLineroDev** [comment]
Hey, I just had the same problem and like you said its npm issue. The thing is that I have it installed, Powershell recognises it but the cmd doesn´t. And running run.bat opens the cmd.
I always install node using nvm and now looks like the official node page have instructions for using fnm wich I found more problematic.

There is this repo called [nvm-windows](https://github.com/coreybutler/nvm-windows/releases) and it´s just super easy to install and then npm works for powershell and cmd
