### ISSUE TITLE
The Save is a steam cloud save

### ISSUE THREAD

**Issue by Communistlord78** [IUrreta/DatabaseEditor#33]
How do you solve the issue of the game saves being steam_autoclad.vdf

**Comment by IUrreta** [comment]
You solve the issue by looking in the correct folder. The Steam_autocloud file is in the saved games folder that is not in the path specified in the readme. Look into AppData/Local/F1 Manager 23 and you should have there your correct saves

**Comment by Communistlord78** [comment]
Yeah thanks it works now, is there a way to edit staff and other data rn?

**Comment by IUrreta** [comment]
Not right now
