### ISSUE TITLE
Marketability attribute doesn't save

### ISSUE THREAD

**Issue by robertdfx127** [IUrreta/DatabaseEditor#330]
When editing the Marketability attribute, when clicking save, you'll get the pop up saying 'save success' etc however if you click off the driver and back onto them, it'll revert to the original value. This happened for Verstappen, Hamilton, Alonso and Leclerc when testing.

**Comment by robertdfx127** [comment]
Actually, nevermind, you can probably close this bug report out. When I close out the database editor and load it back up, it then displays the edited values.

**Comment by IUrreta** [comment]
Yeah, it changes it's just I'm not updating it in the UI. Will be fixed in the next version

**Comment by robertdfx127** [comment]
I believe it's not saving properly actually after a few edits. If I edit 3-4 drivers marketability, it'll save and when I restart, the new value will show. However, at some point after that (maybe around the 5th driver edit), it no longer saves.

**Comment by IUrreta** [comment]
It can’t be that it just “stops working” after 4 or 5 edits, what it might be is not working with staff rather than drivers
