### ISSUE TITLE
[BUG] No Icons and can't see my hired staff's mentality after update.

### ISSUE THREAD

**Issue by JackUnstate** [IUrreta/DatabaseEditor#338]
**Describe the bug**
All the icons are just boxes so I don't know what I am clicking on except from the text!
**To Reproduce**
All the icons are just boxes.

**Expected behavior**
I was under the expectations that I would be able to see all the icons.

**Additional context**
I have not been able to see the icons even when I installed it, I believe the icons are missing from the files.

**Comment by JackUnstate** [comment]
![image](https://github.com/user-attachments/assets/a5b7f7e4-b168-4ac9-ae93-7942e05c8836)

**Comment by IUrreta** [comment]
That is super strange, has the issue solved?
