### ISSUE TITLE
Run.vbs not opening

### ISSUE THREAD

**Issue by LeisurelyStroll** [IUrreta/DatabaseEditor#34]
Hi i have followed all the steps and have my save file downloaded in the correct folder, but when i double click the run vbs file it does not open the game

**Comment by IUrreta** [comment]
Try running launch.bat to see what error  the command prompt throws

**Comment by vSchubii** [comment]
I get the message python.exe not found (at the end) in the console after opening the launcher, although it is installed.

**Comment by IUrreta** [comment]
What else does it say? It's really strange that the app doesn't launch. For Python related errors follow this guide: https://github.com/IUrreta/DatabaseEditor/wiki/Troubleshoot-guide

**Comment by boofun** [comment]
![2K~)%INP8@A9560){I{S0Y7](https://github.com/IUrreta/DatabaseEditor/assets/123930591/172ba6ff-6c22-4823-b35a-3e8eb08740cd)
Seems like I have an issue
run.vbs nor working for me

**Comment by Hiccup3008** [comment]
Hi,
When I open the "run.vbs" file, the following message appears: "Could not connect with backend".
What do I have to do?
Thanks :)

**Comment by Banania23** [comment]
Bonsoir j'ai suivi toute la démarche. Je l'ai réessayé plusieurs fois mais rien à fais en ouvrant le fichier run.vbs un écran blanc apparait.
![Capture d'écran 2023-08-11 211131](https://github.com/IUrreta/DatabaseEditor/assets/142014324/139caef0-af83-41eb-8be8-a585abf2f32a)

J'ai essayé d'ouvrir launch bat mais un plein de codes d'erreurs apparaissent.
![Capture d'écran 2023-08-13 203845](https://github.com/IUrreta/DatabaseEditor/assets/142014324/43a6bae4-2cd4-4672-bf16-5fc3f49efbb2)
 J'ai demandé à plein de personnes sur des serveurs discord mais personne n'a pu m'aider car personne n'a ce problème.
Si tu as une solution cela serait génial.

**Comment by IUrreta** [comment]
> Could someone tell me why Python won't open run.vbs? A window opens and closes instantly.

This was an issue in 1.4.2, should be fixed with 1.4.3, try to update
