### ISSUE TITLE
[BUG]I cant pick saves

### ISSUE THREAD

**Issue by MVPOcean** [IUrreta/DatabaseEditor#346]
**Describe the bug**
I cant pick saves

**To Reproduce**

**Expected behavior**
I can pick saves

**Save file and log.txt**
Attach a link to any file transfer web where you sharen your save and log.txt (located in the same folder as your save in the DBEditor) so I can try to reproduce the bug

**Additional context**

**Comment by IUrreta** [comment]
What even is this issue
