### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by uhervoj** [IUrreta/DatabaseEditor#352]
**Describe the bug**
when I want to get into my old save or start a new one, the game is loading for I dont know how long and i cant play the actual game

**To Reproduce**
dont understand it

**Expected behavior**
I wated to play the game, even tried to uninstall the game and install it again, but it isnt working. 

**Save file and log.txt**
Attach a link to any file transfer web where you sharen your save and log.txt (located in the same folder as your save in the DBEditor) so I can try to reproduce the bug 
dont understand it

**Additional context**
i dont know what to do, whether i will be able to play f1 manager ever again
![Výstřižek](https://github.com/user-attachments/assets/7779f4e0-9f16-4258-9d2a-6244a4cd164e)

**Comment by IUrreta** [comment]
???

**Comment by uhervoj** [comment]
> ???

since i installed database editor, I am stucked on loading screen, that never happened to me before. Now i cant get into my save, When i try to start a new one, the same thing happens

**Comment by IUrreta** [comment]
Brother that has NOTHING to do with the editor, the editor only changes the save you import, it literally CAN’T break your game

**Comment by uhervoj** [comment]
> Brother that has NOTHING to do with the editor, the editor only changes the save you import, it literally CAN’T break your game

well, its weird, that since i installed the editor it doesnt work and this never happened to me before i installed it. But i will try to uninstall f1 manager again and we will see
