### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chill-Blakan** [IUrreta/DatabaseEditor#355]
I opened the editor as usual to change the line up. I chose the driver I want to sign, clicked confirm and the editor disconnected. I restarted it several times, tried different saves, but the problem remained - i cant change line ups. New patch didnt help
Here is my log and saves
https://drive.google.com/drive/my-drive

**Comment by IUrreta** [comment]
You have not shared anything mate. Are you sure you’re filling up all the inputs when clicking confirm in the contract modal?

**Comment by chill-Blakan** [comment]
oh ok, i give too small salary, but still thanks
