### ISSUE TITLE
[FEATURE] editing the full meteorolgy of the races, qualys and practice sessions.

### ISSUE THREAD

**Issue by HGG10** [IUrreta/DatabaseEditor#356]
if i edit the meteorology right now, i don't have the posibility of the race being like Canada 2024 or Great Britain 2024. (wet to dry/dry to inter to dry)
if you can add a button that puts "edit full meteorology" i'll apreciate it.

**Comment by IUrreta** [comment]
Not possible, the weather is stored by a number (state, like dry, wet, cloudy) and then when the race weekend is entered the game generates the full weather based on that state
