### ISSUE TITLE
[BUG] - Desconnected from database after swapping an already contracted Staff member to a vacant position on a team

### ISSUE THREAD

**Issue by PAKarp07** [IUrreta/DatabaseEditor#357]
**Describe the bug**
Desconnected after swapping staff position inside the team. (Example: swapping the race engineer position to a empty space)

**To Reproduce**
1. Go to 'Contracts' and filter by staff
2. Free a space for the staff on any team
3. Drag a contracted staff to the respective free space created at 2. and add the contract

**Expected behavior**

**Save file and log.txt**
![f80d394397cfcbdff4bb407e0181e41d](https://github.com/user-attachments/assets/90728cdb-5623-4708-9915-72ee0f158e4e)

**Additional context**
The bug is detected while editing a save from F1 Manager 2023

**Comment by IUrreta** [comment]
Will be fixed in the next update :)

**Comment by PAKarp07** [comment]
Tested and this issue seems to fixed on the new 2.2.4 version. 
Thank you
