### ISSUE TITLE
[BUG] - Edited save with updates on staff members contracts crashes the game when trying to start a race weekend

### ISSUE THREAD

**Issue by PAKarp07** [IUrreta/DatabaseEditor#358]
**Describe the bug**
After editing contracts of staff members and/or assign them to a new team, the staff members are shown as drivers in game, which crashes the game when launching a race weekend.

**To Reproduce**
1. Go to 'Contracts' and filter by staff
2. Assign new contracts for staff members on any team
3. Launch the game and go to 'Standings' -> 'Championship'       
4. See error (Staff members appear on the driver's championship standings)
5. Advance until a race weekend (Crash happens when started)

**Expected behavior**
Staff contracts should be updated correctly without making the game crash and staff shouldn't appear on the driver's standings

**Save file and log.txt**
Save on the database editor:
![8035e78b1d418bd31cfe5c18b4d32097](https://github.com/user-attachments/assets/05977ac0-134f-4108-ab06-dc21059c76b4)

Save on the game:
![Captura de ecrã 2024-08-25 005633](https://github.com/user-attachments/assets/bc0f4932-f015-41da-9d9c-87cc3b560800)

**Additional context**
The bug is detected while editing a save from F1 Manager 2023 and playing the respective game

**Comment by PAKarp07** [comment]
This is the save used:
[save2.zip](https://github.com/user-attachments/files/16738430/save2.zip)

**Comment by IUrreta** [comment]
What version of the editor did you use to edit their contracts? Can you share with me the log?

**Comment by PAKarp07** [comment]
I used the version 2.2.3. When trying to solve the mistake by myself (by downloading again the database fresh and trying again), I do not have the log that was generated. However, I have this one that has a change to one of the race engineers:

[log.txt](https://github.com/user-attachments/files/16840200/log.txt)

Just a head up to try to help. Line 4 of the log is interesting and could be the problem. The command has the race engineer "Amaury Lardon" with a driverID and other parameters typically for drivers, which makes me believe the database assigns the staff to the same class as drivers. However, since I do not know how the save data and the database itself are working in detail, I could be just plain wrong. 
If the log does not have a clear problem, I can edit a save again and recreate the problem.

**Comment by IUrreta** [comment]
The editor runs the same code for drivers and staff when it comes to contracts, but I put a protection so it doesn't add a non-driver into the standings, but it clearly didn't work out... I'm looking into it, thank's for the help!

**Comment by IUrreta** [comment]
I still haven't found the issue but have added a new layer of protection, should be fixed in the next update, if you want to fix your save in the next update just fire any staff member and hire them again or just swap 2 staff members

**Comment by PAKarp07** [comment]
I did test the new version 2.2.4. After replying all contracts of the staff that were on the driver's championship list, they disappeared and the game now did not crash starting the race weekend.
Meaning, this issue has been fixed. Thank you!
