### ISSUE TITLE
Does not save changes

### ISSUE THREAD

**Issue by IMA-0819** [IUrreta/DatabaseEditor#362]
The guide said to paste my save back onto SaveGames but it still doesn't save after I pasted it back

**Comment by HGG10** [comment]
when you edit something you have tu click the "save changes" button

**Comment by IMA-0819** [comment]
I did click the save changes button

**Comment by HGG10** [comment]
after you end using the database you have to copy the save of the database and paste it in the game

**Comment by IMA-0819** [comment]
i did both save changes button on the right bottom corner and I copied the save of database and paste it back to the saved games file but still it didn't load
