### ISSUE TITLE
Could not connect with backend | No python at

### ISSUE THREAD

**Issue by Tomaszzzz1** [IUrreta/DatabaseEditor#364]
![Zrzut ekranu 2024-09-05 191701](https://github.com/user-attachments/assets/b235fef1-cde2-4d38-a233-a2f7c197c9b4)

![Zrzut ekranu 2024-09-05 191744](https://github.com/user-attachments/assets/698bdb62-5bb4-4eba-ac34-c44bdb045b3e)

I need some help with this if i go into the editor i get no python at then it gets me to the editor and says could not connect with backend

im on windows 11

**Comment by IUrreta** [comment]
https://github.com/IUrreta/DatabaseEditor/wiki/Troubleshoot-guide

**Comment by Tomaszzzz1** [comment]
@IUrreta nothing works

**Comment by Tomaszzzz1** [comment]
f1 manager 23 editor worked idk what happend

**Comment by Tomaszzzz1** [comment]
![image](https://github.com/user-attachments/assets/bf134067-e57f-4265-9cbc-3078be83be37)
do you know why its searching old version of python
