### ISSUE TITLE
[BUG] broken my save file

### ISSUE THREAD

**Issue by CrazyW3063** [IUrreta/DatabaseEditor#373]
When I use the Data base editor it will work fine until a couple races later and it comes up with that one of my car parts are damaged but they aren’t and won’t let me go into a race weekend because it thinks my parts are damaged and there’s no way past that so it kinda ends the career couple races in S1 because I can’t race ( this has happend in lots of saves so ive deleted them all and tried a new save over and over again) , if that makes sense. I then in the database editor created a 2nd upgrade for chasis and front wing to see if that will fix the first problem and i equipped both of them in the editor. then saved the file and put it in my saved games like usual. Now everytime i load the save in game, the game will crash immediately. 

heres the crash files of when i last tried to open my save:

[Breadcrumbs_RHIThread_0.txt](https://github.com/user-attachments/files/16979943/Breadcrumbs_RHIThread_0.txt)
[UEMinidump.dmp](https://github.com/user-attachments/files/16979944/UEMinidump.dmp)

**Comment by IUrreta** [comment]
I hope you have made a backup because this kind of things can happen and are warned all over the place in the repo

**Comment by CrazyW3063** [comment]
> I hope you have made a backup because this kind of things can happen and are warned all over the place in the repo

**Comment by IUrreta** [comment]
I’m sorry but the parts damaged although they aren’t and can’t advance is a common bug, this does not belong here

**Comment by CrazyW3063** [comment]
Apparently it’s a common thing when using the data base editor according to people on the Modded F1 manager 24 Reddit form so it kinda does belong here no ?

**Comment by IUrreta** [comment]
It can also happen to not modded saves, so, no, it does not belong here

**Comment by CrazyW3063** [comment]
Alright cheers then
