### ISSUE TITLE
[BUG] It doesn't work, when changing current teams, to new teams. Like Alpine to Lotus and so.

### ISSUE THREAD

**Issue by surioz** [IUrreta/DatabaseEditor#374]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Save file and log.txt**
Attach a link to any file transfer web where you sharen your save and log.txt (located in the same folder as your save in the DBEditor) so I can try to reproduce the bug

**Additional context**

**Comment by IUrreta** [comment]
Fantastic issue, if you read what it says in the editor you would know those changes are only visuals for the editor
