### ISSUE TITLE
car performance issue

### ISSUE THREAD

**Issue by F1tifosi** [IUrreta/DatabaseEditor#377]
when I edit my car performance before start of the season, it always went well, like I prefer to lower every car's drs effectiveness to decrease the drs train, like all 15% to 30%. it went well at first couple races, but when ai and i start to invent new rear wing part, the designing data doesn't change with my edition and all car become the performance before i edited them after i round development, u have to solve this since with this issue i cant custom my savings with real car performance.

**Comment by IUrreta** [comment]
What does this even mean

**Comment by F1tifosi** [comment]
I mean, I edit my car performance using the editor, but it didnt affect the car designing, so no further effects after 2 or 3 races

**Comment by F1tifosi** [comment]
in normal cases when i design rear wing, it should like 9or 10 percent increase,but if i edit the drs effectiveness before the season from 50 to 20, my design will have like 30 percent increase which made my edition meaningless

**Comment by F1tifosi** [comment]
so i want the car to be like 30% after design but in game it goes to like 60 or 70 percent

**Comment by IUrreta** [comment]
Bro I do not understand you neither I think you understand how car development works
