### ISSUE TITLE
Error: Metadata-generation-failed and the module named websockets cannot be found.

### ISSUE THREAD

**Issue by Utiality** [IUrreta/DatabaseEditor#388]
The database editor starts but before that I get these errors before start up.

I've spent 3 hours now trying to get the editor to pop up, its done it, but now this. I've redownloaded python making sure to click on the check boxes and also downloaded python on the microsft store as advice on the troubleshoot guide but It still does the same thing. Help.

```
   Cython.Compiler.Errors.CompileError: sklearn\linear_model\_cd_fast.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "C:\Users\vinxo\Downloads\DatabaseEditor-release\DatabaseEditor-release\back\back.py", line 2, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'

up to date in 571ms

21 packages are looking for funding
  run `npm fund` for details

> Database Editor F1 Manager@2.3.1 start
> electron .

```

**Comment by IUrreta** [comment]
There’s literally an issue from 3 days ago with this exact name. Please look at previous issues before posting yours

https://github.com/IUrreta/DatabaseEditor/issues/382
