### ISSUE TITLE
[BUG] Can't change driver number. Drop down shows no options.

### ISSUE THREAD

**Issue by rickvand** [IUrreta/DatabaseEditor#390]
**Describe the bug**
When going to Attributes > Drivers, and then at number when trying to change it, the drop down menu does not show any numbers.
I checked on other save files, and on some it does show. So this issue does not always occur.

**To Reproduce**
1. Go to Attributes
2. Click on Drivers
3. At the 'Number' Section, click on the drop down arrow.
4. No list shows up.

**Expected behavior**
I expect a list with available numbers, but instead nothing is shown

**Save file and log.txt**
https://drive.google.com/drive/folders/1HJw5ufGQ8vTzkMBt89CmrTEIqC5E7xLA?usp=sharing

**Additional context**
Version 2.3.1

**Comment by ToPrie** [comment]
Hello, I have a similar problem.

When I open the Database Editor I usually have the option to choose save0, save1 or save2. I have to open a dropdown menu to select any of my saves. The dropdown menu shows nothing - that means I can't use the editor anymore.

Please help :(

**Comment by ToPrie** [comment]
To add at my previous text:

Before that issue I had the issue of 'could not connect with backend' I already tried all of the solutions of the creator (https://github.com/IUrreta/DatabaseEditor/wiki/Troubleshoot-guide) after deinstalling python and then reinstalling the newest version via a link (https://www.python.org/downloads/) the problem of the dropdown menu I previously mentioned happend...

**Comment by IUrreta** [comment]
What does this have to do with not being able to change driver numbers?

**Comment by KaiN-31** [comment]
Actually, this bug has been around for about half a month ,  just forgot to report

**Comment by ToPrie** [comment]
> What does this have to do with not being able to change driver numbers?

Well it is more or less the same dropdown menu problem, only I just can't open any saves anymore...

**Comment by ToPrie** [comment]
> > Actually, this bug has been around for about half a month , just forgot to report
> 
> This is not a bug, it's a consequence of the game assigning numbers to every affiliate that teams hire. The dropdown only shows available numbers

Well that still doesn't solve my problem... :/

**Comment by rickvand** [comment]
> of

Okay, so this behaviour I got is expected?

Maybe as a feature request it would be great if you can switch driver numbers regardless of if they are taken or not?

**Comment by rickvand** [comment]
> > This is not a bug, it's a consequence of the game assigning numbers to every affiliate that teams hire. The dropdown only shows available numbers
> 
> Okay, so this behaviour I got is expected?
> 
> Maybe as a feature request it would be great if you can switch driver numbers regardless of if they are taken or not?

**Comment by IUrreta** [comment]
> > > Actually, this bug has been around for about half a month , just forgot to report
> > 
> > 
> > This is not a bug, it's a consequence of the game assigning numbers to every affiliate that teams hire. The dropdown only shows available numbers
> 
> Well that still doesn't solve my problem... :/

Brother this issue has NOTHING to do with yours, literally, nothing

**Comment by ToPrie** [comment]
Man whats my issue then :(

**Comment by IUrreta** [comment]
> > This is not a bug, it's a consequence of the game assigning numbers to every affiliate that teams hire. The dropdown only shows available numbers
> 
> Okay, so this behaviour I got is expected?
> 
> Maybe as a feature request it would be great if you can switch driver numbers regardless of if they are taken or not?

At firts (in f1M 23), this wasn't an issue, nor was the expected behaviour, then they started messing up with affiliates numbers post-launch in 24 and I just haven't given thiss issue enough priority. I'll try to fix this for the next update.

**Comment by ToPrie** [comment]
> > > > Actually, this bug has been around for about half a month , just forgot to report
> > > 
> > > 
> > > This is not a bug, it's a consequence of the game assigning numbers to every affiliate that teams hire. The dropdown only shows available numbers
> > 
> > 
> > Well that still doesn't solve my problem... :/
> 
> Brother this issue has NOTHING to do with yours, literally, nothing

Well, I am sorry to bother you again, but I somehow fixed my issue... I don't know what I did, or how I did it, but now I don't have that 'could not connect with backend' issue anymore.

Now I have another Problem. Now when I try to edit anyones contract everything is empty. I can't find anything in your troubleshoot guide and couldn't find anyone with the same problem.

Am I even in the right chat to ask such questions or should I be opening a new discussion? I feel so lost right now, sorry for everyone...
