### ISSUE TITLE
[BUG] - "Something went wrong please restart the tool"

### ISSUE THREAD

**Issue by ToPrie** [IUrreta/DatabaseEditor#391]
**Describe the bug**
"Somethig went wrong please restart the tool" message, whenever trying to open any save

**Expected behavior**
"Connected succesfully" message, and the the Editor working as intendet

**Additional context**
Whenever I try to startup and open my save in the Database editor the previously mentioned message pops up. Although I have acces to all of the 'windows' like contracts or performance, everything is empty. In the Troubleshoot guide (https://github.com/IUrreta/DatabaseEditor/wiki/Troubleshoot-guide) this error is only mentioned when editing driver stats and contracts and not when loading up the save. I can't figure out any solution for myself, so I hope to find any help here.

![image](https://github.com/user-attachments/assets/a2663b7c-d6b0-4105-a22b-a029d9934002)
![image](https://github.com/user-attachments/assets/859ecf34-464f-476f-9a1d-3e9993446334)
![image](https://github.com/user-attachments/assets/50000b9d-8c5b-4db8-9f98-8dfe2be9f10a)

**Comment by ToPrie** [comment]
Is there any quick solution to fix that problem?

**Comment by IUrreta** [comment]
Unfortunately, no

**Comment by ToPrie** [comment]
Does that mean, that I have to start a new save, or will this problem also occure on new saves?

**Comment by IUrreta** [comment]
It means it will keep happening if you edit it the same way as you have done to that save

**Comment by ToPrie** [comment]
ok? But what did I do wrong in the first place for that to happen?

I'm really sorry to ask such dumb questions, but I really do not know what I did wrong, what I can do to prevent this or to fix the problem. I just want to play the game and have a little fun editing contracts and performance.

**Comment by IUrreta** [comment]
How do you expect me to know what exactly did you do to your save without having your save?

**Comment by ToPrie** [comment]
Is it possible that I somehow send you my save?

**Comment by ToPrie** [comment]
> How do you expect me to know what exactly did you do to your save without having your save?

[save0.zip](https://github.com/user-attachments/files/17610765/save0.zip)
