### ISSUE TITLE
cannot run database editor

### ISSUE THREAD

**Issue by 4aronn** [IUrreta/DatabaseEditor#393]
i cannot run database editor but i get this error 
![{6C256C07-3E38-40DD-B429-CF56D7CC31B9}](https://github.com/user-attachments/assets/725f346c-e76c-4b92-91c7-a9681840bd9b)

**Comment by 4aronn** [comment]
nvm i am stupid and i got it to work

**Comment by CJloHuK3** [comment]
4aronn, how you repaired this issue?
