### ISSUE TITLE
Could not connect with backend

### ISSUE THREAD

**Issue by gojinh** [IUrreta/DatabaseEditor#395]
Whenever I run run.bat the message "could not connect with backend" appears. I've already tried all the solutions in the solutions guide, but nothing worked! What can I do to fix it? Screenshots are attached.
![Captura de tela 2024-11-09 212714](https://github.com/user-attachments/assets/fe9a3c90-18a8-4f9d-92cc-b9b384661ef3)
![Captura de tela 2024-11-09 212732](https://github.com/user-attachments/assets/0d3fcc5d-c95e-433b-9eef-c168cb77fe2d)
![Captura de tela 2024-11-09 212907](https://github.com/user-attachments/assets/701ba6b1-5ce3-446d-8879-4fb035b335df)

**Comment by CJloHuK3** [comment]
gojinh, how you repaired this issue?
