### ISSUE TITLE
[BUG] despite following every instruction and every troubleshooting suggestion, i still have the same problem with 'unable to connect'

### ISSUE THREAD

**Issue by shevchjenko** [IUrreta/DatabaseEditor#403]
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "C:\Users\djenk\OneDrive\Desktop\f1mdb\DatabaseEditor\back\back.py", line 2, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'

it opens editor but doesnt connect

**Comment by LegalSmeagol** [comment]
Same for me. Regardless of the troubleshooting steps, issue still occurs so version must be inherently bugged/broken.
