### ISSUE TITLE
[BUG] Editor Disconnected when I try load save file 

### ISSUE THREAD

**Issue by Lukasix-cze** [IUrreta/DatabaseEditor#409]
**Describe the bug**
Hi, I have a problem. When I try to load a save in the editor, the editor automatically disconnects and says "something went wrong."

**Expected behavior**
To be able load the save 

**Save file and log.txt**
https://mega.nz/file/P2YB3QRY#UdLDk2Zih13XV6SVngAWm8DjR_e5QV3h-MSlnQic_ck
[log.txt](https://github.com/user-attachments/files/18081922/log.txt)

**Comment by IUrreta** [comment]
That is because your save file is modified

**Comment by Lukasix-cze** [comment]
> That is because your save file is modified by an external factor that is not the editor
But I didn't do anything else with it; I just added custom liveries to the game.
Will it be possible to fix it somehow?

**Comment by IUrreta** [comment]
Then you must have installed another mod that modifies the base databasd
