### ISSUE TITLE
BUG! WHAT IS THIS?

### ISSUE THREAD

**Issue by OllieTaylor12** [IUrreta/DatabaseEditor#411]
![image](https://github.com/user-attachments/assets/f324b879-df75-40fc-91dc-dfe8521c1b0b)

**Comment by OllieTaylor12** [comment]
![image](https://github.com/user-attachments/assets/38e52e13-a202-4e51-b8b0-4c6692728f2c)
now its saying this?!

**Comment by IUrreta** [comment]
Read.

**Comment by OllieTaylor12** [comment]
> Read.

i literally did, dont know why there's rudeness.
