### ISSUE TITLE
[BUG] Could not connect with backend

### ISSUE THREAD

**Issue by Belugato** [IUrreta/DatabaseEditor#412]
**Describe the bug**
when I launch the database, I get a "could not connect with backend" error message and when I try to see backups there are none.
thank you and I hope you will be able to solve the problem.

![Capture](https://github.com/user-attachments/assets/5c42e270-d31f-44b8-b7a6-92c52d9af69b)
![image](https://github.com/user-attachments/assets/9e8d6a8b-6441-4d06-8f78-5423634d3b16)

**Comment by djbyrne43** [comment]
yeah i have the same issue i cant load my file, let me know if you find a fix. Did you install it by the zip perchance? Maybe this method is broken right now

**Comment by djbyrne43** [comment]
![image](https://github.com/user-attachments/assets/c97b228c-f475-4db1-921a-08b3ef57251e)

**Comment by djbyrne43** [comment]
nevermind, tried the other method and it also didnt work

**Comment by Belugato** [comment]
Yep I tried both nothing works. Also tried different versions of python and node.js but nothing works

**Comment by Belugato** [comment]
Do you have the right version of python ? Not 3.13.

**Comment by djbyrne43** [comment]
yeh im on 3.12.8 and its still the same issue

**Comment by Int3gr4al** [comment]
I had this issue. took off version 3.13 , installed 3.12.8 making sure i ticked the "Add to PATH" box on first screen of the installer. 
On the last screen of installer I also allowed it to bypass the 255 char limit.
Ran the run.bat again and it worked perfectly

**Comment by Belugato** [comment]
Mhhh ok I will try this

**Comment by Belugato** [comment]
Ok I solved the problem by uninstalling all python versions of my computer then reinstall the 3.12.8

**Comment by Int3gr4al** [comment]
> Ok I solved the problem by uninstalling all python versions of my computer then reinstall the 3.12.8

Good to hear 🙂

**Comment by IUrreta** [comment]
Who would have thought doing the things said in the installation guide and the troubleshooting guides would have made it work?
