### ISSUE TITLE
[BUG] metadata-generation-failed

### ISSUE THREAD

**Issue by Cwojdek** [IUrreta/DatabaseEditor#413]
**Describe the bug**
Whenever I try to run Database editor  I get an error note saying "metadata-generation-failed" in cmd and then when it launch I get an error saying "Could not connect with backend". Reinstalling python and downloading database editor again did not help

I do not know how to recreate the bug. It happen the moment I try to run the program

**Expected behavior**
I expected it to run

**Save file and log.txt**
[Version 2.3.3 error logs.txt](https://github.com/user-attachments/files/18197074/Version.2.3.3.error.logs.txt)
I did not even run a save file yet

**Additional context**
![ss](https://github.com/user-attachments/assets/8c2a2899-7ac6-4969-843f-006da6ad2304)

**Comment by IUrreta** [comment]
Troubleshoot guide is there for a reason
