### ISSUE TITLE
New Feature: Editing engine stats

### ISSUE THREAD

**Issue by KillCroop2** [IUrreta/DatabaseEditor#47]
I would love to see a feature that allows users to edit engine stats.

**Comment by olegozi** [comment]
Yes please

**Comment by IUrreta** [comment]
Hey, it's comming in the next update. 1.4 is a very big update and it's taking some time, but it will come out soon :)

**Comment by IUrreta** [comment]
Unfortunately, the feature didn't quite meet my quality standards and it's not comming out with 1.4.0, but I will try my best to improve it with time and I'll try to release it as soon as it's ready
