### ISSUE TITLE
Having error installing electron

### ISSUE THREAD

**Issue by boofun** [IUrreta/DatabaseEditor#49]
![image](https://github.com/IUrreta/DatabaseEditor/assets/123930591/c64f22d5-0593-462b-822f-bd7b98fde581)

**Comment by IUrreta** [comment]
Normally this is due to unstable connections. One guy from China reported this issue to me on discord and managed to solve it. Maybe search online for potential fixes? It's not a common issue.

**Comment by boofun** [comment]
Yeah i am in China right now. Thanks anyway

**Comment by boofun** [comment]
Solved.
