### ISSUE TITLE
Can't open F1 Manager Save File

### ISSUE THREAD

**Issue by xysa12** [IUrreta/DatabaseEditor#50]
I've installed the save editor for F1 Manager 23. However, when I want to drag and drop the save file, the save editor can't open it. Therefore, I can't use the editor. The save selector is empty, no matter how many times I drag&drop the save file. 

Here I attached the details. Hope you can help. Thanks 

![F1 Manager 23 Details](https://github.com/IUrreta/DatabaseEditor/assets/142068862/0337bc16-b6be-4a0f-adfe-68031d259b0e)

**Comment by IUrreta** [comment]
Do you get the Could not connect with backend error?

**Comment by strakkyno** [comment]
Hi mate, solved with a clear uninstall fours pythons from  control panel and reinstall. Is possible imploment an option in pilots stats to change age?


Thx mate 🙂
________________________________
Da: IUrreta ***@***.***>
Inviato: sabato 12 agosto 2023 17:27
A: IUrreta/DatabaseEditor ***@***.***>
Cc: strakkyno ***@***.***>; Manual ***@***.***>
Oggetto: Re: [IUrreta/DatabaseEditor] Can't open F1 Manager Save File (Issue #50)


Do you get the Could not connect with backend error?
