### ISSUE TITLE
Would it be possible to have a video to follow along?

### ISSUE THREAD

**Issue by Airwane** [IUrreta/DatabaseEditor#52]
I follow best with a video, as I'm not a coder.

Also, would it be possible to do all this in Microsoft Visual Studio?

**Comment by IUrreta** [comment]
I'm afraid I'm not understanding what your problem is

**Comment by ronneberg1** [comment]
I think he is asking for an instructional step-by-step video guide on how to get the editor to work

**Comment by Airwane** [comment]
It's fine, I found a way to do it. thanks for this tool! It's Awesome

**Comment by Airwane** [comment]
done

**Comment by Airwane** [comment]
you can delete this now thanks
