### ISSUE TITLE
cant edit the line ups of Apha thauri and Willliams

### ISSUE THREAD

**Issue by panda2700** [IUrreta/DatabaseEditor#57]
I have just installed this mod and its working great exept one thing, i cant edit the line ups from alpa thauri and williams. The screens stops and i cant scroll down.
![Schermopname (102)](https://github.com/IUrreta/DatabaseEditor/assets/142183317/aae5e54b-238b-4129-acbd-24175dd3f4af)

**Comment by IUrreta** [comment]
Check if your screen resolution is above 125%. If your screen is  1080p and you have it in 150% or more you won't be able to see it fully

**Comment by panda2700** [comment]
yep it worked! thank you for your fast service, im really enyoing your mod!
