### ISSUE TITLE
Game is not updated

### ISSUE THREAD

**Issue by panda2700** [IUrreta/DatabaseEditor#58]
I updated the ratings of a few drivers, removed Imola from the calender, and changed some reserve drivers. None of the changes have been saved. When i go back in the save everything is the same.

The rest is working good, i dont know what im doing wrong.

**Comment by IUrreta** [comment]
You're not pasting back the save in the save folder, or Your'e pasting the wrong one

**Comment by panda2700** [comment]
Ooh i did not knew that, thank you! It works now, and thanks again for the fast response
