### ISSUE TITLE
My Save Game is not being found by the database editor

### ISSUE THREAD

**Issue by kingdeen8** [IUrreta/DatabaseEditor#59]
I followed all the steps, and the database editor cannot seem to find my save game. 
![Screenshot (114)](https://github.com/IUrreta/DatabaseEditor/assets/142263656/688b703c-9344-4449-ab28-3293e70c18ab)

**Comment by panda2700** [comment]
i had that the first time too, try restarting the mod. it worked for me

**Comment by IUrreta** [comment]
Please for that error read this: https://github.com/IUrreta/DatabaseEditor/wiki/Troubleshoot-guide
