### ISSUE TITLE
Could not connect with backend issue

### ISSUE THREAD

**Issue by PixelFastFood** [IUrreta/DatabaseEditor#62]
Keep getting this error, but the troubleshooting doesn't seem to work. I wanna also note that with installing Python I didn't get the option to check the boxes like showed in the example, while having used the same version. When opening via launch.bat I get: 

Version: 1.4.2
Requirement already satisfied: websockets in c:\users\marni\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (11.0.3)
Traceback (most recent call last):
  File "C:\Users\marni\DatabaseEditor\back\back.py", line 2, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'

up to date in 681ms

21 packages are looking for funding
  run `npm fund` for details

> electron-quick-start@1.0.0 start
> electron .

I'm probs just overlooking smth but thought I'd post it here anyways

**Comment by IUrreta** [comment]
This is really odd. The `Requirement already satisfied: websockets in c:\users\marni\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (11.0.3)` Is literally saying that you have the library websockets installed and the `ModuleNotFoundError: No module named 'websockets'` is saying the opposite.

**Comment by JustMyra** [comment]
Same issue here.

Editing launch.bat

**start "" /B py back.py**

to 

**start "" /B python back.py**

seems to have fixed the issue.
