### ISSUE TITLE
Crash to desktop -- did I screw my save?

### ISSUE THREAD

**Issue by pedersenkirk2** [IUrreta/DatabaseEditor#63]
After installing the tool and making some very light changes, the game now crashes every time I try to load my saved game. I've attached the readout I get when the game crashes from the Unreal Engine, but I'm not sure what to do next. 

Is there a way to fix this, or am I screwed? 

Thanks. 
![CTDT-readout](https://github.com/IUrreta/DatabaseEditor/assets/142356645/69b8796b-60f3-430b-b7fa-179f4cce76b4)

**Comment by IUrreta** [comment]
What exact changes did you make? You can see them in the log.txt. Doing driver transfers during weekends or the day just before may cause in a crash when loading the weekend. I don't know what can cause a crash when loading the save. You can try to do the reverse of the changes you made, but your save is most likely gone. That's why it's highly recommend in the readme to do a backup before editing it.

**Comment by pedersenkirk2** [comment]
The changes I made were pretty minor. I only adjusted some team sliders and driver ratings, nobody was moved. 

This was the entirety of it: 

- [2023-08-15 12:49:54.581817] INFO: Command executed: connect
- [2023-08-15 12:49:57.900765] INFO: Command executed: saveSelected save3.sav
- [2023-08-15 13:44:27.538150] INFO: Command executed: 
- [2023-08-15 14:02:00.177515] INFO: Command executed: editPerformance 7 0 1 1 1 0 0
- [2023-08-15 14:02:03.831534] INFO: Command executed: editPerformance 7 0 1 1 1 0 0
- [2023-08-15 14:02:22.294771] INFO: Command executed: editPerformance 1 0 -1 -1 -1 0 0
- [2023-08-15 14:02:27.207887] INFO: Command executed: editPerformance 3 0 -1 -1 -1 0 0
- [2023-08-15 14:03:22.105012] INFO: Command executed: editStats 130 0 77 79 85 69 74 72 67 74 74 90 84
- [2023-08-15 14:03:30.955390] INFO: Command executed: editStats 120 0 84 76 78 72 75 66 78 76 72 89 76
- [2023-08-15 14:04:16.255349] INFO: Command executed: editStats 285 0 82 72 81 77 72 80 80 80 76 87 80
- [2023-08-15 14:04:55.489173] INFO: Command executed: editStats 378 0 74 66 70 64 68 70 77 80 72 95 87
- [2023-08-15 14:14:49.520513] INFO: Command executed: editPerformance 1 -1 0 0 0 0 0
- [2023-08-15 14:26:43.562676] INFO: Command executed: calendarbah0 sau0 aus0 aze0 mia0 imo0 mon0 spa0 can1 aut0 gbr0 hun0 bel0 ned0 ita0 jap0 sgp0 qat0 usa0 mex0 bra0 veg0 uae1

Do you leave the file in the database editor, or bring it back and save over it in Saved Games? That might be it.

**Comment by IUrreta** [comment]
I don't see anything strange in the log. What do you mean by bring it back and save over it in Saved Games? If you don't paste back the edited save into the saved games folder you shouldn't see any changes in game. Did you make this changes before the first race of the season?

**Comment by pedersenkirk2** [comment]
> I don't see anything strange in the log. What do you mean by bring it back and save over it in Saved Games? If you don't paste back the edited save into the saved games folder you shouldn't see any changes in game. Did you make this changes before the first race of the season?

Right now, I'm in race 17/23 of 2024, so it's not in the beginning of the season. 

All I meant by bring it back was moving the file back to saved games, but it sounds like I did that correctly.

**Comment by IUrreta** [comment]
Yeah, if you moved the save back into the saved games folder that is correct. The only thing I can see that causes the crash is editing the cslendar mid-season, which is not advised in the readme. If you did not make a backup, you may find the old version of your save in the windows bin

**Comment by IUrreta** [comment]
Don't you have an autosave from it or smth? If youw ant, you can send me your save file and tomorrow I can try a few things to try to fix it

**Comment by pedersenkirk2** [comment]
It's very kind of you to offer, but I wouldn't want to waste your time. It was my mistake.

**Comment by IUrreta** [comment]
Don't worry man, I really want to help you. I know how bad it can feel to loose such a long save. I can't promise anything but if you send it I'll do my besy

**Comment by pedersenkirk2** [comment]
Thank you, I really do appreciate it. How can I send you the file?

**Comment by SantiROG2019** [comment]
Iurreta crees que podrías hacer tu magia con el editor y en un futuro cercano poder editar la edad de los pilotos y el staff?

**Comment by SantiROG2019** [comment]
Basado en tu experiencia tu crees que la actualización 1.6 del F1 manager 23 qué arregla lo de la investigación para el año siguiente aplique para partidas comenzadas o solo para partidas nuevas?. Gracias

**Comment by IUrreta** [comment]
> Thank you, I really do appreciate it. How can I send you the file?

You can send it to my email ignacioutato@gmail.com or attach them to a reply here

**Comment by IUrreta** [comment]
> Iurreta crees que podrías hacer tu magia con el editor y en un futuro cercano poder editar la edad de los pilotos y el staff?

Creo que es posible, sí, igual lo miro para la versión 1.5

**Comment by pedersenkirk2** [comment]
> > Thank you, I really do appreciate it. How can I send you the file?
> 
> You can send it to my email [ignacioutato@gmail.com](mailto:ignacioutato@gmail.com) or attach them to a reply here

Thank you again. I've emailed you the file. Please let me know if I can assist further.

**Comment by SantiROG2019** [comment]
> > Basado en tu experiencia tu crees que la actualización 1.6 del F1 manager 23 qué arregla lo de la investigación para el año siguiente aplica para partidas comenzadas o solo para partidas nuevas?. Gracias
> 
> Cual es el problema exactamente? not engo el juego por lo que no se de que bug me hablas

Hay un bug en el juego que hace que no obtengas todos los beneficios de las investigaciones para el año siguiente cuando deslizas las barras hacia un lado o hacia otro lado. Solo obtienes los beneficios correctos de las investigaciones si dejas los sliders en el centro y no tocas nada

**Comment by IUrreta** [comment]
> > > Thank you, I really do appreciate it. How can I send you the file?
> > 
> > 
> > You can send it to my email [ignacioutato@gmail.com](mailto:ignacioutato@gmail.com) or attach them to a reply here
> 
> Thank you again. I've emailed you the file. Please let me know if I can assist further.

Just to confirm, previous to the calendar change you put like almost every race with a sprint right?
