### ISSUE TITLE
Random control stat change 

### ISSUE THREAD

**Issue by JustDerDennis** [IUrreta/DatabaseEditor#64]
After using the tool and playing the save file for a bit, one of the drivers control stat decreases to 50-60. This only occurs when using the db editor. Playing the game without ever using the db editor does not lead to the stat decrease. 
Swapping the driver out with someone else only helps for 1-2 races before the driver also gets the decrease in control.

**Comment by IUrreta** [comment]
And? What do you want me to do? That has nothing to do with me. This is the first time I hear something like this. If that's what happens, is the first time I hear it. That has to do with the game. In 22 it didn't happen to anyone. It might be a bug. I don't know what do you want to achieve with this, honestly, it's out of my control.

**Comment by IUrreta** [comment]
Just for informing, this thing that this guy came here and said it's not a problem caused by the editor, it's a side effect from a sponsorship obligation. Please inform yourself before ranting someone 😉
