### ISSUE TITLE
Unable to launch a GP

### ISSUE THREAD

**Issue by iSeith** [IUrreta/DatabaseEditor#67]
Hello,

After a few driver and calendar transfers, it's impossible for me to launch a GP. I'm stuck with my performance targets, but I can't go on and launch the GP. Do you have a solution? 

Thanks in advance.

**Comment by IUrreta** [comment]
I don't understand what do you mena by "stuck with my performance targets"

**Comment by iSeith** [comment]
Sorry, mb
I wanted to say that I'm stuck on "race preparation" and "performance targets"
I can't start the GP game
