### ISSUE TITLE
Alex Albon disappeared from the database

### ISSUE THREAD

**Issue by toffi3** [IUrreta/DatabaseEditor#85]
Okey, so i was playing Williams and i just got into 2026 season, i am before 4th race of the season which in my case is Monaco and i decided to replace Alex Albon with Lando Norris (I did it at the beginning of the previous season by signing a contract for the next season - it being 2026, the one i am currently in) and i did just that and i noticed that Alex is gone from contracts free drivers section as well as from editing driver's statistics section. I thoght, maybe it's because he's retiring but no, that's not the case, i can offer him a contract in game, he's listed as an free agent. And of course i have 1.5.3 DBE Version.

Before i go tho i'd like to see that the tool is great and without it the game would be very boring because it gives so many oportunities. Thanks for creating such a great tool and i'd like to offer my ideas, of course if they are possible to do
1. Editing Board Objectives
2. Editing Random Events, Regulations that happen within the emails
3. Adding possiblity to save "Presets" that would automaticaly do a set of commands when starting a new save because it's very exhausting when starting a new save that you have to edit everything all over again manually and it's usually takes like 10 minutes in my example
4. I don't really think that adding new drivers/teams would be possible but that would be amazing
5. Possiblity for any stat being 100 because for some reason maximum you can set in the database is 99 (For Example on every new save there is a driver called Nikola Tsolov that has 100 Growth value)

Oh and you won't probably solve my issue without my save o here it is: https://easyupload.io/59p1qu

Have a great day!

**Comment by IUrreta** [comment]
Hey, first of all, thanks for giving so much context and information for the bug, and for providing a save, you really made me save some huge time! Second, thanks again! You are correct, Albon is nowhere to be seen in the Editor with your save loaded. Fortunately, I have found the issue and I'm working on a fix :)

**Comment by IUrreta** [comment]
Fixed and updated :)
Regarding your 5 suggestions:
1. Doable, might come in the next big update, but I can't promise
2. Tried to mess around with that in 22 and I was not successful, might be doable but will take time to investigate and understand
3. This one I don't think it's possible, it will have to take into account many many factors as what is the starting point of a preset, if it's not the same when you want to execute it, the tool might crash, also, what do you consider a command? it's not easy and that will most likely not come and even not taken a look into
4. Unfortunately not possible with the editor
5. Yeah this is easily doable :)

**Comment by toffi3** [comment]
Regarding the third point, if you look into log.txt of the database everything you do is listed as an command
Example text from the log
"[2023-08-14 21:38:31.187935] INFO: Command executed: connect
[2023-08-14 21:38:46.574600] INFO: Command executed: saveSelected save1.sav
[2023-08-14 21:39:37.715023] INFO: Command executed: hire 82 9 3 848000 30000 0 1 2028
[2023-08-14 21:40:18.043598] INFO: Command executed: editStats 1 0 96 98 97 92 90 95 97 90 90 16 57
[2023-08-14 21:40:47.792705] INFO: Command executed: editStats 2 0 97 96 89 90 90 92 94 90 90 80 32
[2023-08-14 21:41:18.045749] INFO: Command executed: editStats 3 0 85 84 83 85 85 82 86 85 83 75 81
[2023-08-14 21:41:42.707096] INFO: Command executed: editStats 8 0 90 90 91 83 86 88 88 84 94 34 29
[2023-08-14 21:42:29.511009] INFO: Command executed: editStats 10 0 95 97 85 93 99 98 97 98 93 75 70
[2023-08-14 21:42:53.372797] INFO: Command executed: editStats 11 0 90 91 93 85 85 93 95 90 90 54 22"

What i mean by this point is that you could save a bunch of those commands into one specific file and then you could trigger all of the commands at once with the click of a button rather than editing everything manually over and over again for every save. It would save a lot of time
