### ISSUE TITLE
Issue with the 'pip' installation

### ISSUE THREAD

**Issue by GaTcha-Sama** [IUrreta/DatabaseEditor#94]
Hello
When I paste "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py" and run the command, it is writen :"Warning: Failed to open the file get-pip.py: Permission denied" and two lines bellow "curl: (23) Failure writing output to destination"

What can I do please?

Thank you
![problem pip (2)](https://github.com/IUrreta/DatabaseEditor/assets/121195670/89445b8b-6df1-4407-91d5-d22c9faaf975)

**Comment by Zottegie** [comment]
same here..

**Comment by dillong481** [comment]
Did you ever figure out the problem?

**Comment by IUrreta** [comment]
A lotof people have find useful to install python from the microsoft store
