### ISSUE TITLE
nothing fixes "can't connect to backend"

### ISSUE THREAD

**Issue by ibach7** [IUrreta/DatabaseEditor#95]
I've tried everything in the troubleshooting guide multiple times and nothing will fix the problem. No matter what I do, I keep getting "can't connect to backend"

**Comment by IUrreta** [comment]
What does the command prompt say when launching with launch.bat?

**Comment by ibach7** [comment]
Version: 1.5.6
Requirement already satisfied: websockets in c:\users\noah\appdata\local\programs\python\python311\lib\site-packages (11.0.3)
Traceback (most recent call last):
  File "C:\Users\noah\Desktop\DatabaseEditor-1.5.6\DatabaseEditor-1.5.6\back\back.py", line 2, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'

up to date in 586ms

21 packages are looking for funding
  run `npm fund` for details

> electron-quick-start@1.0.0 start
> electron .

**Comment by Veriloquent** [comment]
I had this issue myself, if you are on windows 11 it may be the same as my issue, this is how I solved it.

When trying to install pip, Python seems to have been trying to run python.exe from C:\Python311, but on windows 11 it seems to install the .exe in C:\Users\(username)\AppData\Local\Programs\Python\Python311, I copy/pasted the entire contents of the python folder from C:\Users\(username)\AppData\Local\Programs\Python\Python311 and pasted it into C:\Python311 then had to go to the folder in C:\Python311 and allow full read/write access to user for the entire folder, then when I tried to install pip it worked perfectly, at this point I loaded up the database editor and it was working.

**Comment by ibach7** [comment]
that fixed it, thanks
